/*
 Generated by typeshare 1.13.3
*/

/**
 * An angle in radians, always in (-pi, pi]. This type supports safe arithmetic
 * operations:
 * 
 * ```ignore
 * # use dies_core::Angle;
 * let a = Angle::from_degrees(90.0);
 * let b = Angle::from_degrees(45.0);
 * let c = a + b;
 * assert_eq!(c.degrees(), 135.0);
 * ```
 */
export type Angle = number;

export type DebugValue = 
	| { type: "Shape", data: DebugShape }
	| { type: "Number", data: number }
	| { type: "String", data: string }
	| { type: "Plan", data: PlanData };

/**
 * A map of debug messages.
 * 
 * # Key format
 * 
 * The keys should always be `snake_case` and should only contain alphanumerical
 * characters. The `.` character is reserved for separating different parts of the key.
 * 
 * Keys can be arbitrary, but there are some patterns that are recognized by the
 * UI:
 * - `p{player_id}.{value}`: A value associated with a player.
 */
export type DebugMap = Record<string, DebugValue>;

export type PlayerId = number;

/** Coarse classification of an announcer line, used by the UI for icon/color. */
export enum AnnouncementCategory {
	/** Generic state/info transition (Halt, Stop, Run, Force start, Timeout). */
	Info = "Info",
	/** A stoppage reason (ball out of field, no progress). */
	Stoppage = "Stoppage",
	FreeKick = "FreeKick",
	Kickoff = "Kickoff",
	Penalty = "Penalty",
	/** Ball placement related. */
	Placement = "Placement",
	/** A foul or rule violation. */
	Foul = "Foul",
	/** A card was issued. */
	Card = "Card",
	Goal = "Goal",
}

/**
 * # Team-Specific Coordinate System
 * 
 * This module provides coordinate system transformations to create a consistent
 * team-specific reference frame where the +x axis always points towards the
 * enemy goal, regardless of which side of the field the team is defending.
 * 
 * ## Coordinate System Philosophy
 * 
 * In RoboCup SSL, teams can be assigned to defend either the positive or negative
 * x side of the field. To simplify strategy code, we transform all coordinates
 * into a team-specific coordinate system where:
 * 
 * - **+x axis**: Always points towards the enemy goal (attacking direction)
 * - **-x axis**: Always points towards our own goal (defending direction)
 * - **y axis**: Remains unchanged (left/right from team perspective)
 * 
 * ## How It Works
 * 
 * The transformation is based on two key pieces of information:
 * 1. **SideAssignment**: Which team (Blue/Yellow) defends the positive x side
 * 2. **TeamColor**: The color of our team (Blue/Yellow)
 * 
 * ### Transformation Rules
 * 
 * - If our team attacks in the same direction as world +x: coordinates remain unchanged
 * - If our team attacks in the opposite direction: x coordinates are negated, angles are mirrored
 */
export enum TeamColor {
	Blue = "Blue",
	Yellow = "Yellow",
}

/**
 * A single line in the announcer commentary feed, formatted backend-side from
 * referee commands, game events, and (in sim) the simulator's own events so it
 * reads identically for sim and live matches.
 */
export interface Announcement {
	/**
	 * Monotonic id, unique within a session. The UI uses it to dedupe and to
	 * detect freshly-arrived lines (which animate in at full opacity).
	 */
	id: number;
	/** World time (seconds) when the line was minted. */
	timestamp: number;
	category: AnnouncementCategory;
	/** The team the line concerns, if any — used to tint the line. */
	team?: TeamColor;
	/**
	 * Human-readable commentary, e.g. "Free kick — Blue" or
	 * "Throw-in: ball left field, last touched by Yellow".
	 */
	text: string;
}

export interface AutorefKickedBall {
	/** The initial position [m] from which the ball was kicked */
	pos: Vector2;
	/** The initial velocity [m/s] with which the ball was kicked */
	vel: Vector3;
	/** The unix timestamp [s] when the kick was performed */
	start_timestamp: number;
	/** The predicted unix timestamp [s] when the ball comes to a stop */
	stop_timestamp?: number;
	/** The predicted position [m] at which the ball will come to a stop */
	stop_pos?: Vector2;
}

export interface AutorefInfo {
	kicked_ball?: AutorefKickedBall;
}

export interface AutorefKickedBallTeam {
	/** The initial position [m] from which the ball was kicked */
	pos: Vector2;
	/** The initial velocity [m/s] with which the ball was kicked */
	vel: Vector3;
	/** The unix timestamp [s] when the kick was performed */
	start_timestamp: number;
	/** The predicted unix timestamp [s] when the ball comes to a stop */
	stop_timestamp?: number;
	/** The predicted position [m] at which the ball will come to a stop */
	stop_pos?: Vector2;
	/** The robot that kicked the ball */
	robot_id: PlayerId;
	we_kicked: boolean;
}

/**
 * Tuning for the two-layer collision-avoidance stack (global planner + ORCA)
 * and the shared obstacle model they both read.
 * 
 * All distances are millimetres, times are seconds. A single `AvoidanceConfig`
 * is shared across the whole team and applied live from settings updates.
 */
export interface AvoidanceConfig {
	/**
	 * ORCA's emergency margin on top of the two-robot contact distance [mm].
	 * ORCA is a last-resort reactive backstop, so keep this small (≈0) — the
	 * planner does the real avoidance with `planner_margin`. The planner inflates
	 * robots by `robot_clearance + planner_margin`; ORCA only by this.
	 */
	robot_clearance: number;
	/**
	 * Base inset of the robot centre from the physical field walls [mm]. The
	 * effective per-robot inset is `wall_care * wall_margin` (see
	 * `PlayerControlInput::wall_care`): a robot may request a tighter margin
	 * (down to 0 = edge-at-wall) to reach a ball hard against the boundary.
	 */
	wall_margin: number;
	/** Keep-out margin grown around each defense area [mm]. */
	defense_margin: number;
	/** Ball keep-out radius during `Stop` [mm] (rule: stay 500 mm clear). */
	ball_stop_radius: number;
	/** Base ball keep-out radius when `avoid_ball` is set [mm]. */
	ball_base_radius: number;
	/** Additional ball keep-out radius scaled by `avoid_ball_care` [mm]. */
	ball_care_scale: number;
	/** How far ahead moving robots are extrapolated at constant velocity [s]. */
	robot_extrapolation: number;
	/**
	 * ORCA time horizon τ [s]: how far ahead reciprocal collisions are
	 * resolved. Kept short so ORCA only fires for imminent collisions, not in
	 * normal play (planned avoidance handles the rest).
	 */
	time_horizon: number;
	/**
	 * Speed below which a robot counts as "stationary" for reciprocity gating
	 * [mm/s]. A stationary robot does not yield to a moving one — the mover
	 * takes the full avoidance burden.
	 */
	stationary_speed: number;
	/**
	 * Prefer steering around obstacles over braking for them: drop ORCA's
	 * cut-off-circle projection so a constrained velocity is deflected (turned)
	 * rather than slowed. Avoids the "sticky crawl" where ORCA suppresses speed
	 * near an obstacle. Falls back to the 3-D LP when genuinely boxed in.
	 */
	prefer_steering: boolean;
	/** Only robots within this distance are considered ORCA neighbours [mm]. */
	neighbor_dist: number;
	/** Cap on the number of neighbours folded into a single ORCA LP. */
	max_neighbors: number;
	/** Grid cell size for the planner's any-angle search [mm]. */
	grid_resolution: number;
	/**
	 * The planner's robot-avoidance margin [mm]: it routes paths clear of
	 * robots by `robot_clearance + planner_margin`. This is the primary
	 * avoidance — keep it comfortable so ORCA rarely needs to engage.
	 */
	planner_margin: number;
	/**
	 * Replan only when the target has moved more than this [mm] (hysteresis to
	 * suppress path flicker).
	 */
	replan_target_tol: number;
	/**
	 * Run the global path planner. When false, the follower steers straight at
	 * the target and only ORCA provides avoidance.
	 */
	planner_enabled: boolean;
	/**
	 * Run ORCA reciprocal avoidance. When false, the path-follower velocity
	 * passes through untouched (useful for isolating layers when debugging).
	 */
	orca_enabled: boolean;
	/**
	 * Honor per-robot `hold_ground` requests: a flagged robot (concerto's
	 * shadow wall) scales its ORCA responsibility toward opponents by closing
	 * -speed attribution, so it refuses to be deflected by a charging attacker
	 * while still fully avoiding opponents it is itself driving toward. When
	 * false, opponents always get full responsibility (pre-hold-ground
	 * behavior).
	 */
	orca_hold_ground: boolean;
}

export interface TeamPlayerId {
	team_color: TeamColor;
	player_id: PlayerId;
}

/**
 * A physical contest over the ball, *orthogonal* to ownership: at least one
 * robot from each team is crowding a near-stationary ball. Fires even while the
 * ball reads `Owned` (our breakbeam latches ownership the instant we touch it,
 * hiding an opponent pressing from the far side — the deadlock the strategy
 * otherwise can't see).
 */
export interface BallContest {
	/** Robots from *both* teams within `contest_dist` of the ball this frame. */
	near: TeamPlayerId[];
}

/** A struct to store the ball state from a single frame. */
export interface BallData {
	/**
	 * Unix timestamp of the recorded frame from which this data was extracted (in
	 * seconds). This is the time that ssl-vision received the frame.
	 */
	timestamp: number;
	/** Position of the ball filtered by us, in mm, in dies coordinates */
	position: Vector3;
	/** Raw position as reported by vision */
	raw_position: Vector3[];
	/** Velocity of the ball in mm/s, in dies coordinates */
	velocity: Vector3;
	/** Whether the ball is being detected */
	detected: boolean;
}

/** Status of the RF basestation itself, surfaced to the bench UI. */
export interface BaseStationInfo {
	connected: boolean;
	protocol_ok: boolean;
	version: string;
	protocol_version: string;
	/** Current radio channel in MHz. */
	channel_mhz: number;
	num_radios: number;
	/** Online flag per radio module. */
	radios_online: boolean[];
	max_robots: number;
	/** Radio command packets the client transmits per second (1 s window). */
	tx_hz?: number;
	/**
	 * Robot feedback frames the client receives per second, summed over all
	 * robots (1 s window).
	 */
	rx_hz?: number;
	/**
	 * Actual frequency of the client's IO loop (target is 50 Hz); a value well
	 * below target means the client can't keep up with the serial link.
	 */
	loop_hz?: number;
	/**
	 * Worst-case send-loop iteration work time over the last second, in
	 * microseconds (time spent before the pacing sleep). A spike here means
	 * the loop periodically stalls, delaying that robot's next setpoint —
	 * jitter a 1 s-averaged `loop_hz` would hide.
	 */
	work_max_us?: number;
	/**
	 * Fraction of send-loop iterations in the last second whose work alone met
	 * or exceeded the target period (loop ran flat-out with no pacing slack).
	 * ~0 = healthy headroom; ~1 = serial/RF-bound saturation.
	 */
	overrun_frac?: number;
}

/** The status of a sub-system on the robot */
export enum SysStatus {
	Emergency = "Emergency",
	Ok = "Ok",
	Ready = "Ready",
	Stop = "Stop",
	Starting = "Starting",
	Overtemp = "Overtemp",
	NoReply = "NoReply",
	Armed = "Armed",
	Disarmed = "Disarmed",
	Safe = "Safe",
	NotInstalled = "NotInstalled",
	Standby = "Standby",
	Cooldown = "Cooldown",
}

/** State of the firmware reflex-kick state machine. */
export enum ReflexKickState {
	Off = "Off",
	Armed = "Armed",
	Cooldown = "Cooldown",
	Emergency = "Emergency",
}

/** Echo of the last command the robot reports having received (global frame). */
export interface CommandEcho {
	global_speed_x: number;
	global_speed_y: number;
	heading_setpoint: number;
	heading_last_measurement: number;
	dribbler_speed: number;
	kick_time: number;
	/** Raw `Radio_RobotCommand` code; the frontend maps it to a label. */
	robot_command: number;
}

/** Firmware version reported by a robot. */
export interface FirmwareVersion {
	major: number;
	minor: number;
	patch: number;
}

/** A message from one of our robots to the AI */
export interface PlayerFeedbackMsg {
	/** The robot's ID */
	id: PlayerId;
	primary_status?: SysStatus;
	kicker_status?: SysStatus;
	imu_status?: SysStatus;
	tof_status?: SysStatus;
	kicker_cap_voltage?: number;
	kicker_temp?: number;
	motor_statuses?: [SysStatus, SysStatus, SysStatus, SysStatus, SysStatus];
	motor_speeds?: [number, number, number, number, number];
	motor_temps?: [number, number, number, number, number];
	breakbeam_ball_detected?: boolean;
	breakbeam_sensor_ok?: boolean;
	pack_voltages?: [number, number];
	/** IMU readings: [ang_x, ang_y, ang_z, ang_wx, ang_wy, ang_wz] */
	imu_readings?: [number, number, number, number, number, number];
	motor_currents?: [number, number, number, number, number];
	main_board_current?: number;
	avg_loop_time_us?: number;
	max_loop_time_us?: number;
	smart_kick_counter?: number;
	kick_ok_flag?: boolean;
	reflex_kick_state?: ReflexKickState;
	reflex_kick_counter?: number;
	breakbeam_raw?: number;
	tof_ball_detected?: boolean;
	/**
	 * Time-of-flight ball position estimate `[x, y]` in raw sensor units
	 * (`x` signed −left/+right, `y` unsigned +forward/−back).
	 */
	tof_xy?: [number, number];
	/**
	 * Time-of-flight detection confidence (raw sensor byte, `0..=255`), from
	 * glue's `tof_confidence()`. `None` when the robot reports no reading.
	 * Consumed by the per-robot ToF-backup breakbeam substitute.
	 */
	tof_confidence?: number;
	last_command?: CommandEcho;
	firmware_version?: FirmwareVersion;
	/**
	 * Rate at which fresh feedback frames are arriving from this robot,
	 * measured backend-side over a 1 s sliding window. Saturates at the
	 * basestation read rate (~50 Hz) — useful for watching it collapse under
	 * radio load, not as an absolute ceiling.
	 */
	feedback_hz?: number;
	/** Age of the most recent feedback frame in milliseconds. */
	feedback_age_ms?: number;
	/**
	 * Whether the robot is currently considered online by the basestation
	 * (fresh feedback within glue's 400 ms timeout).
	 */
	online?: boolean;
}

export interface BasestationResponse {
	blue_team: PlayerFeedbackMsg[];
	yellow_team: PlayerFeedbackMsg[];
	unknown_team: PlayerFeedbackMsg[];
	/** RF basestation status (radios, version, channel), for the test bench. */
	base_info?: BaseStationInfo;
}

export enum ConsoleLogLevel {
	Trace = "Trace",
	Debug = "Debug",
	Info = "Info",
	Warn = "Warn",
	Error = "Error",
}

/** A single backend log line streamed to the console panel. */
export interface ConsoleLogMessage {
	level: ConsoleLogLevel;
	/** Log target (module path). */
	target: string;
	message: string;
	/** Milliseconds since UNIX epoch at emission time. */
	ts_ms: number;
}

/**
 * Settings for the low-level controller.
 * 
 * Every field here is consumed by `PlayerController` or one of its
 * subcontrollers (`PathFollower`, `YawController`).
 * Low-level controller limits and path-follower tuning. The translational path
 * follower (`PathFollower`) produces a speed profile (cruise / cornering /
 * braking-to-goal) and the player controller applies a first-order asymmetric
 * acceleration clamp; `YawController` handles heading.
 */
export interface ControllerSettings {
	/** Acceleration cap when speeding up (mm/s²). */
	max_acceleration: number;
	/**
	 * Deceleration cap when slowing down (mm/s²); also the braking authority the
	 * follower's speed profile plans against.
	 */
	max_deceleration: number;
	/** Speed cap on the commanded velocity magnitude (mm/s). */
	max_velocity: number;
	/**
	 * Lateral (cornering) acceleration cap (mm/s²) — sets how fast the robot may
	 * carry through a path corner.
	 */
	lateral_acceleration: number;
	/**
	 * Proportional arrival gain (1/s): commanded speed eases off as `kp ×
	 * remaining distance` into corners and the goal. Over-damped (no overshoot);
	 * lower = gentler/earlier braking, higher = later/snappier.
	 */
	approach_kp: number;
	/**
	 * Active-braking gain for the terminal approach. When the robot is
	 * overspeeding relative to the proportional arrival profile, the commanded
	 * velocity is pushed *below* the profile (and may reverse) by `brake_gain ×
	 * overspeed`, and the acceleration slew clamp is bypassed so the firmware
	 * reverse-thrusts to a hard stop. `0` = disabled (gentle proportional only);
	 * `1` roughly mirrors the overspeed into a reverse command. Per-robot
	 * overridable via `PlayerControlInput::brake_gain`.
	 */
	brake_gain?: number;
	/** Minimum pure-pursuit lookahead distance (mm), used at low speed. */
	lookahead_min: number;
	/** Pure-pursuit lookahead time (s): lookahead = clamp(time·speed, min, max). */
	lookahead_time: number;
	/** Maximum angular velocity (rad/s). */
	max_angular_velocity: number;
	/**
	 * Maximum angular acceleration (rad/s²) — passed to YawController as the
	 * upper bound on its planned angular accel.
	 */
	max_angular_acceleration: number;
	/** Proportional gain for heading tracking. */
	angle_kp: number;
	/** Heading deadzone (rad) — yaw control outputs zero inside this band. */
	angle_cutoff_distance: number;
}

/** Which control the UI should render for a parameter. */
export enum ParamKind {
	Bool = "Bool",
	Float = "Float",
	Int = "Int",
	Text = "Text",
}

/**
 * A strategy's declaration of one parameter: how to label/render it, and its
 * default value (used when no override has been pushed yet).
 */
export interface ParamSpec {
	key: string;
	label: string;
	kind: ParamKind;
	default: ParamValue;
}

/**
 * One team's strategy parameters (declared specs + current values), surfaced to
 * the UI via `ExecutorInfo`.
 */
export interface TeamStrategyParams {
	team: TeamColor;
	specs: ParamSpec[];
	values: Record<string, ParamValue>;
}

/**
 * Code-generated description of one tunable knob, surfaced to the web UI to
 * render a control. Values themselves are stored separately in
 * `ExecutorSettings::skill_tunables` keyed by [`TunableSpec::key`].
 */
export interface TunableSpec {
	/** Namespaced unique key, `"<module>.<NAME>"` (the settings-map key). */
	key: string;
	/** Human label derived from the knob name (Title Case). */
	label: string;
	/** Help text from the knob's doc comment, if any. */
	help?: string;
	/** Compile-time default (shown when no override is set; revert target). */
	default: number;
	min?: number;
	max?: number;
	step?: number;
	/** Display unit suffix (e.g. `"mm"`, `"mm/s"`, `"s"`, `"rad"`). */
	unit?: string;
	/** Grouping label for the UI; defaults to the module/skill name. */
	section?: string;
}

/** Runtime information about the active executor. */
export interface ExecutorInfo {
	/** Whether the executor is currently paused. */
	paused: boolean;
	/** The player IDs that are currently controlled manually. */
	manual_controlled_players: TeamPlayerId[];
	/** Which teams are currently active/controlled. */
	active_teams: TeamColor[];
	/** Declared parameters + current values for each active team's strategy. */
	strategy_params: TeamStrategyParams[];
	/**
	 * Code-generated metadata for the executor's skill tunables (one entry per
	 * knob declared with `tunables!`). Drives the dynamic Skill settings tab;
	 * current values live in `ExecutorSettings::skill_tunables`.
	 */
	skill_tunable_specs: TunableSpec[];
}

/** Runtime information about the active executor. */
export interface ExecutorInfoResponse {
	info?: ExecutorInfo;
}

/** A field mask for the `WorldTracker`. */
export interface FieldMask {
	x_min: number;
	x_max: number;
	y_min: number;
	y_max: number;
}

/**
 * Settings for the `WorldTracker`.
 * 
 * Kalman variances are unit-time process noise (`*_unit_transition_var`,
 * in mm²/s for the constant-velocity model) and measurement variance
 * (`*_measurement_var`, in mm²). Higher transition variance → tracker
 * trusts measurements more (snappier, noisier). Higher measurement
 * variance → tracker trusts dynamics model more (smoother, laggier).
 */
export interface TrackerSettings {
	/**
	 * Vision crop applied at the ball tracker — fractions of the field
	 * half-extent. Defaults to the full field.
	 */
	field_mask: FieldMask;
	/**
	 * Constant-velocity process noise (white-noise *acceleration* PSD). Used when
	 * `player_use_acceleration` is false.
	 */
	player_unit_transition_var: number;
	/**
	 * Constant-acceleration process noise (white-noise *jerk* PSD). Used when
	 * `player_use_acceleration` is true. On a totally different numeric scale from
	 * the CV value, which is why it is a separate field — toggling the model must
	 * not silently leave the wrong process-noise magnitude in place.
	 */
	player_ca_unit_transition_var: number;
	/**
	 * Measurement noise for the player position Kalman filter (mm²). Should match
	 * the real vision noise floor (~0.4 mm² measured on hardware).
	 */
	player_measurement_var: number;
	/**
	 * Use a constant-acceleration motion model (state x,vx,ax,…) for players
	 * instead of constant-velocity. The CA model anticipates sustained
	 * acceleration, cutting the onset/transient velocity lag in hard maneuvers.
	 */
	player_use_acceleration: boolean;
	/**
	 * Feed the commanded velocity into the filter's predict step as a first-order
	 * lag toward the setpoint (feedforward). Reduces lag further during commanded
	 * maneuvers. EXPERIMENTAL — needs field tuning of `player_command_tau`.
	 */
	player_use_command_feedforward?: boolean;
	/**
	 * First-order time constant (s) for command feedforward: the predicted velocity
	 * relaxes toward the commanded velocity with this τ. ~robot velocity-loop
	 * response time. Only used when `player_use_command_feedforward` is true.
	 */
	player_command_tau: number;
	/**
	 * EWMA factor for the player yaw low-pass filter — 0 = no filtering,
	 * 1 = freeze.
	 */
	player_yaw_lpf_alpha: number;
	/** Process noise for the ball position/velocity Kalman filter (mm²/s). */
	ball_unit_transition_var: number;
	/** Measurement noise for the ball position Kalman filter (mm²). */
	ball_measurement_var: number;
	/**
	 * Minimum vision confidence for a ball detection to be accepted. Some camera
	 * setups report near-zero confidence even for a clean ball, so this defaults
	 * low — raise it only if your vision reports trustworthy confidence values.
	 */
	ball_confidence_threshold: number;
}

/**
 * Represents which team defends the positive x side of the field.
 * 
 * In RoboCup SSL, the field coordinate system is fixed, but teams can be
 * assigned to defend either side. This enum tracks that assignment.
 */
export enum SideAssignment {
	/** Blue team defends the positive x side (+x goal) */
	BlueOnPositive = "BlueOnPositive",
	/** Yellow team defends the positive x side (+x goal) */
	YellowOnPositive = "YellowOnPositive",
}

/** Team configuration that can be set before executor creation. */
export interface TeamConfiguration {
	/** Whether the blue team is active */
	blue_active: boolean;
	/** Whether the yellow team is active */
	yellow_active: boolean;
	/** Which team defends the positive x side */
	side_assignment: SideAssignment;
	/** IPC strategy binary name for blue team (None = no strategy) */
	blue_strategy?: string;
	/** IPC strategy binary name for yellow team (None = no strategy) */
	yellow_strategy?: string;
}

export enum Handicap {
	NoKicker = "no_kicker",
	NoDribbler = "no_dribbler",
	NoBreakbeam = "no_breakbeam",
}

export interface TeamSpecificSettings {
	handicaps: Record<PlayerId, Handicap[]>;
	/**
	 * Per-robot ToF-backup breakbeam toggle. For a robot in this set, the
	 * hardware breakbeam bit is *ignored entirely* for possession and the
	 * Schmitt-triggered onboard ToF signal stands in as its breakbeam. Robots
	 * not in the set use the hardware breakbeam as normal. Thresholds are
	 * global (see `PossessionConfig::tof_backup_*`).
	 */
	tof_backup_breakbeam: HashSet<PlayerId>;
	/**
	 * Testing override: when true, this team ignores the Game Controller and
	 * always plays as if in free play (`GameState::Run`) — full speed, no
	 * halt/stop/kickoff positioning, no rule keep-out zones. Useful for
	 * testing on the real field with no GC connected, or for letting one team
	 * keep playing while the other is stopped. Defaults to false.
	 */
	ignore_gc: boolean;
}

/**
 * Tunable parameters for the unified possession metric. One central home for
 * every threshold that used to be scattered across the strategy and the pass
 * coordinator. Distances in mm, times in seconds, speeds in mm/s.
 */
export interface PossessionConfig {
	/** Ball-to-robot distance at which a robot *gains* possession (near band). */
	acquire_dist: number;
	/**
	 * Looser distance at which the current owner *retains* possession. Must be
	 * `>= acquire_dist`; the gap is the hysteresis that prevents oscillation.
	 */
	release_dist: number;
	/**
	 * Breakbeam is ignored unless the ball is within this distance of the robot
	 * (rejects spurious sensor triggers with the ball nowhere near).
	 */
	breakbeam_gate_dist: number;
	/**
	 * Frames a proximity-only possession change must persist before it commits.
	 * Breakbeam-confirmed gains bypass this and commit in one frame.
	 */
	acquire_frames: number;
	/**
	 * If the second-closest candidate is within this margin of the closest, the
	 * state is `Contested` instead of `Owned`.
	 */
	ambiguity_margin: number;
	/**
	 * A ball faster than this can't be claimed by proximity (breakbeam still can,
	 * for a robot genuinely carrying it).
	 */
	max_ball_speed: number;
	/**
	 * How long to hold the last stable possession while the ball is undetected
	 * before decaying to `Loose`. The belief is marked `stale` while holding.
	 */
	hold_secs: number;
	/**
	 * After a commanded kick, suppress the kicker's *proximity* re-acquisition for
	 * this long (breakbeam re-acquisition is never suppressed).
	 */
	release_suppress_secs: number;
	/**
	 * An *opposing* robot within this distance of the ball counts as pressing it.
	 * Deliberately looser than `acquire_dist` (a presser sits ~one robot-radius
	 * out, so it never registers as a proximity owner — which is why contests
	 * were invisible). Used only by the contest signal, not ownership.
	 */
	contest_dist: number;
	/**
	 * The ball must be slower than this for a contest to register — a genuine pin
	 * is ~stationary. Far tighter than `max_ball_speed`; a moving ball means
	 * someone is already winning, so there's nothing to resolve.
	 */
	contest_speed_max: number;
	/** Frames a contest must persist before it commits (react fast — urgent). */
	contest_enter_frames: number;
	/**
	 * Frames an absent contest must persist before it clears (release slow — don't
	 * drop on a single jittery opponent-position frame).
	 */
	contest_exit_frames: number;
	/** ToF confidence must exceed this for the raw detection to hold (`c_th`). */
	tof_backup_conf_th: number;
	/** Raw detection requires `|tof_x| < x_th` (`x_th`, sensor units). */
	tof_backup_x_th: number;
	/** Raw detection requires `tof_y < y_th` (`y_th`, sensor units). */
	tof_backup_y_th: number;
	/** Frames the raw condition must hold before the latch turns ON (`N`). */
	tof_backup_enter_frames: number;
	/** Frames the raw condition must fail before the latch turns OFF (`M`). */
	tof_backup_exit_frames: number;
}

/** Settings for the executor. */
export interface ExecutorSettings {
	controller_settings: ControllerSettings;
	tracker_settings: TrackerSettings;
	team_configuration: TeamConfiguration;
	yellow_team_settings: TeamSpecificSettings;
	blue_team_settings: TeamSpecificSettings;
	/**
	 * Runtime overrides for executor *skill* tunables (the knobs declared with
	 * `tunables!` in `dies-executor`'s skills), keyed by their namespaced key
	 * (`"<skill>.<NAME>"`). Holds **overrides only** — an absent key uses the
	 * compile-time default. The render metadata (label/help/range/unit) is
	 * code-generated and surfaced separately via `ExecutorInfo::skill_tunable_specs`.
	 * Persisted with the rest of the settings, so it rides the baseline/revert bar.
	 */
	skill_tunables?: Record<string, number>;
	/** Tuning for the unified ball-possession metric (computed in the world tracker). */
	possession_config?: PossessionConfig;
	allow_no_vision: boolean;
	/**
	 * Global on/off for goal-area avoidance. When false, both compliance and
	 * the controller skip the goal-area keep-out logic (goalkeeper exception
	 * is irrelevant since the whole feature is off).
	 */
	goal_area_avoidance: boolean;
	/**
	 * Collision-avoidance tuning (obstacle margins + global planner + ORCA).
	 * Applied live to the planner and ORCA solver.
	 */
	avoidance?: AvoidanceConfig;
}

export interface ExecutorSettingsResponse {
	settings: ExecutorSettings;
}

/** A single field arc -- eg. the center circle */
export interface FieldCircularArc {
	/** Readable name of the arc */
	name: string;
	/** Center of the arc, in dies coordinates */
	center: Vector2;
	radius: number;
	a1: number;
	a2: number;
	thickness: number;
}

/** A single field line segment */
export interface FieldLineSegment {
	/** Readable name of the line segment */
	name: string;
	/** Start Vector2 of the line segment, in dies coordinates */
	p1: Vector2;
	/** End Vector2 of the line segment, in dies coordinates */
	p2: Vector2;
	/** Thickness of the line segment, in mm */
	thickness: number;
}

/** The field geometry. */
export interface FieldGeometry {
	/** Field length (distance between goal lines) in mm */
	field_length: number;
	/** Field width (distance between touch lines) in mm */
	field_width: number;
	/** Goal width (distance inner edges of goal posts) in mm */
	goal_width: number;
	/** Goal depth (distance from outer goal line edge to inner goal back) in mm */
	goal_depth: number;
	/** Boundary width (distance from touch/goal line centers to boundary walls) in mm */
	boundary_width: number;
	/** Generated line segments based on the other parameters */
	line_segments: FieldLineSegment[];
	/** Generated circular arcs based on the other parameters */
	circular_arcs: FieldCircularArc[];
	/** Penalty area depth (distance from goal line to penalty mark) in mm */
	penalty_area_depth: number;
	/** Penalty area width (distance from penalty mark to penalty area edge) in mm */
	penalty_area_width: number;
	/** Center circle radius in mm */
	center_circle_radius: number;
	/** Distance from goal line to penalty mark in mm */
	goal_line_to_penalty_mark: number;
	/** Ball radius in mm */
	ball_radius: number;
}

/** A single robot's saved pose in a field snapshot (position + yaw, no velocity). */
export interface RobotSnapshot {
	id: PlayerId;
	position: Vector2;
	yaw: Angle;
}

/** The game state, as reported by the referee. */
export type GameState = 
	| { type: "Unknown",  }
	| { type: "Halt",  }
	| { type: "Timeout",  }
	| { type: "Stop",  }
	| { type: "PrepareKickoff",  }
	| { type: "BallReplacement", data: Vector2 }
	| { type: "PreparePenalty",  }
	| { type: "Kickoff",  }
	| { type: "FreeKick",  }
	| { type: "Penalty",  }
	| { type: "PenaltyRun",  }
	| { type: "Run",  };

/**
 * A saved simulator field state: robot poses + ball position, plus an optional
 * game state to seed. Replayed by teleporting everything back into place (see
 * `Simulation::apply_snapshot`) and, when present, forcing the auto-referee into
 * `game_state` for `operating_team`. Both game-state fields are optional so
 * older positional-only snapshots still load.
 */
export interface FieldSnapshot {
	blue: RobotSnapshot[];
	yellow: RobotSnapshot[];
	ball?: Vector2;
	/** Game state captured with the snapshot, if any. Seeded on load. */
	game_state?: GameState;
	/**
	 * Team that operates `game_state` (kickoff/free-kick/penalty/placement).
	 * Ignored for symmetric states (run/stop/halt).
	 */
	operating_team?: TeamColor;
}

export interface GameStateData {
	/** The state of current game */
	game_state: GameState;
	/**
	 * If we are the main party currently performing tasks in the state.
	 * true for symmetric states(halt stop run timout)
	 */
	us_operating: boolean;
	yellow_cards: number;
	/**
	 * The player who performed the freekick, if it was us (for double touch tracking)
	 * Only Some until another player touches the ball
	 */
	freekick_kicker?: PlayerId;
	/**
	 * Our robot barred from touching the ball by the double-touch rule (the
	 * restart taker, once the ball is in play and released). `None` while the
	 * taker is still legally taking the kick, and when the taker is theirs.
	 */
	double_touch_barred?: PlayerId;
	max_allowed_bots: number;
	our_keeper_id?: PlayerId;
	/**
	 * The restart the GC's `next_command` hint predicts will resume play after
	 * the current stoppage (free kick / kickoff / penalty), if any. Used to
	 * pre-stage during Stop/BallReplacement. `None` when there is no meaningful
	 * hint. This never affects rule compliance — that keys off `game_state`.
	 */
	predicted_next_game_state?: GameState;
	/**
	 * Whether the predicted restart ([`Self::predicted_next_game_state`]) is
	 * ours to take, in team-relative terms. `None` when there is no prediction.
	 */
	predicted_us_operating?: boolean;
}

export interface GetDebugMapResponse {
	debug_map: DebugMap;
}

/** A recorded log available for replay (directory or `.dieslog` zip). */
export interface LogInfo {
	name: string;
	path: string;
	session_start_unix: number;
	duration_s?: number;
	end_unix?: number;
	frame_count: number;
	is_simulation: boolean;
	blue_strategy?: string;
	yellow_strategy?: string;
	is_zip: boolean;
}

export interface LogsResponse {
	logs: LogInfo[];
}

/**
 * A struct to store the player state from a single frame.
 * Live per-robot open-loop delay estimate (command → first visible motion on
 * vision), computed online from stop→go events via the same √displacement
 * x-intercept extrapolation used offline. Only populated for own players, and
 * only once at least one clean event has been measured. The rolling window is
 * anchored to the most recent event, so a robot that sits still does not lose
 * its last estimate — `age_s` tells you how stale it is.
 */
export interface OpenLoopDelayStats {
	/** Median measured delay (ms) over the rolling window. */
	median_ms: number;
	/** Maximum measured delay (ms) over the rolling window. */
	max_ms: number;
	/** Seconds since the most recent measured event (staleness of the estimate). */
	age_s: number;
	/** Number of events in the rolling window. */
	sample_count: number;
}

/** One step of a strategy [`DebugValue::Plan`]. */
export interface PlanStep {
	/**
	 * Category (e.g. `"Capture"`, `"Shoot"`, `"Pass"`, `"Dribble"`), used by
	 * the UI for an icon / color.
	 */
	kind: string;
	/** Short label for the step. */
	label: string;
	/** Optional detail line (targets, partners, etc.). */
	detail?: string;
	/** Whether this is the step currently being executed. */
	active: boolean;
}

/**
 * A strategy's current plan: an ordered list of steps driven by one robot.
 * A structured, plan-shaped debug primitive (distinct from field shapes), shown
 * in the UI's plan panel.
 */
export interface PlanData {
	/** The robot id (if any) driving the plan. */
	active_robot?: number;
	/** The plan's steps, in order. */
	steps: PlanStep[];
}

/**
 * Execution state of a player's active skill, mirroring the executor's
 * `SkillStatus` without coupling `dies-core` to the strategy protocol.
 */
export enum SkillState {
	/** No skill has been commanded for this player. */
	Idle = "Idle",
	/** The skill is currently executing. */
	Running = "Running",
	/** The skill completed successfully. */
	Succeeded = "Succeeded",
	/** The skill failed. */
	Failed = "Failed",
}

/**
 * A snapshot of the skill a (own-team) player is currently executing, surfaced
 * to the UI. Populated by the executor from the active skill's own report.
 */
export interface PlayerSkillInfo {
	/** Short skill type name, e.g. `"GoToPos"`, `"Shoot"`, `"Pass"`. */
	skill_type: string;
	/** Execution state. */
	state: SkillState;
	/**
	 * Human-readable description of the skill's internal state, e.g.
	 * `"approaching ball"` or `"aiming"`.
	 */
	description: string;
}

/**
 * Why a robot is present on the field but not an assignable roster member.
 * 
 * Both cases are physically on the field (still avoided as obstacles) but must
 * never be handed to the strategy as a controllable player:
 * - `RadioLost`: seen by vision but the RF/basestation link is gone, so we
 * cannot command it (non-cooperative — teammates take full avoidance).
 * - `CardRemoved`: benched by the team controller for a yellow card and driven
 * off-field (still cooperative — it moves under our ORCA control).
 */
export enum SidelineReason {
	RadioLost = "RadioLost",
	CardRemoved = "CardRemoved",
}

export interface PlayerData {
	/**
	 * Unix timestamp of the recorded frame from which this data was extracted (in
	 * seconds). This is the time that ssl-vision received the frame.
	 */
	timestamp: number;
	/** The player's unique id */
	id: PlayerId;
	/** Unfiltered position as reported by vision */
	raw_position: Vector2;
	/** Position of the player filtered by us in mm, in dies coordinates */
	position: Vector2;
	/** Velocity of the player in mm/s, in dies coordinates */
	velocity: Vector2;
	/**
	 * Yaw of the player, in radians, (`-pi`, `pi`), where `0` is the positive
	 * x direction, and `pi/2` is the positive y direction.
	 */
	yaw: Angle;
	/** Unfiltered yaw as reported by vision */
	raw_yaw: Angle;
	/** Angular speed of the player (in rad/s) */
	angular_speed: number;
	/**
	 * EWMA-smoothed position noise floor in mm — RMS of the Kalman innovation
	 * (raw vision vs. constant-velocity prediction). Useful for diagnosing
	 * whether downstream controllers are tracking sensor noise.
	 */
	position_noise: number;
	/** The overall status of the robot. Only available for own players. */
	primary_status?: SysStatus;
	/** The voltage of the kicker capacitor (in V). Only available for own players. */
	kicker_cap_voltage?: number;
	/** The temperature of the kicker. Only available for own players. */
	kicker_temp?: number;
	/** The voltages of the battery packs. Only available for own players. */
	pack_voltages?: [number, number];
	/**
	 * Raw breakbeam sensor reading (only meaningful for own players). An *input*
	 * to the possession metric and kept for logging — not a consumer-facing
	 * signal. Use `has_ball` (or `WorldData::possession`) instead.
	 */
	breakbeam_ball_detected: boolean;
	/**
	 * Unified "this player has the ball" signal, derived from
	 * `WorldData::possession` (true iff this player is the confident owner).
	 */
	has_ball: boolean;
	/**
	 * Whether the onboard ToF ball sensor is reporting `Ok` (only meaningful for
	 * own players). Used as the magnet-mode capability gate — `Standby`/etc. and
	 * robots without the sensor read `false`.
	 */
	tof_ok: boolean;
	/**
	 * Whether the onboard ToF sensor currently sees the ball in its ~64 mm front
	 * window (only meaningful for own players). The magnet-mode engage trigger.
	 */
	tof_ball_detected: boolean;
	/**
	 * Raw ToF ball-position estimate `[x, y]` in sensor units (`x` signed
	 * −left/+right, `y` unsigned +forward/−back). Only meaningful for own
	 * players; `None` when the sensor reports nothing. An *input* to the
	 * ToF-backup breakbeam substitute — use `has_ball`, not this.
	 */
	tof_xy?: [number, number];
	/**
	 * Raw ToF detection confidence byte (`0..=255`); `None` when the robot
	 * reports no reading. Input to the ToF-backup breakbeam substitute.
	 */
	tof_confidence?: number;
	/**
	 * Whether this robot's per-robot ToF-backup breakbeam toggle is on. When
	 * true, the hardware breakbeam bit is ignored for possession and the
	 * Schmitt-triggered ToF signal (`tof_backup_ball_detected`) stands in.
	 */
	tof_backup_enabled: boolean;
	/**
	 * Latched output of the ToF-backup Schmitt trigger (only meaningful when
	 * `tof_backup_enabled`). Stamped from the possession tracker, mirrors how
	 * `has_ball` is filled — for logging/tuning, not a consumer signal.
	 */
	tof_backup_ball_detected: boolean;
	imu_status?: SysStatus;
	imu_readings?: [number, number, number, number, number, number];
	kicker_status?: SysStatus;
	/**
	 * State of the firmware reflex-kick state machine, as reported over feedback
	 * (only meaningful for own players; `None` when the robot reports nothing).
	 * `Armed` means the kicker will fire the instant the ball trips the beam.
	 * Surfaced for logging/UI; skills may read it to confirm the firmware armed.
	 */
	reflex_kick_state?: ReflexKickState;
	/**
	 * The skill this player is currently executing, if known. Only populated
	 * for own players (the team we control); `None` for opponents and when no
	 * skill is active.
	 */
	skill?: PlayerSkillInfo;
	handicaps: HashSet<Handicap>;
	/**
	 * Set when this robot is on the field but not an assignable roster member
	 * (radio lost, or card-removed). `None` for normal players and opponents.
	 * Robots with this set are forked out of `TeamData::own_players` into
	 * `TeamData::sidelined_players` but remain in the color lists.
	 */
	sideline?: SidelineReason;
	/**
	 * Live open-loop delay estimate (own players only). `None` until the first
	 * clean stop→go event has been measured. Stamped by the executor.
	 */
	open_loop_delay?: OpenLoopDelayStats;
}

/** Who controls the ball, in absolute (team-tagged) terms. */
export type PossessionState = 
	/** Nobody clearly controls the ball. */
	| { type: "Loose",  }
	/** A single robot confidently controls the ball. */
	| { type: "Owned", data: {
	owner: TeamPlayerId;
}}
	/** Multiple robots are equally plausible owners and can't be disambiguated. */
	| { type: "Contested", data: {
	candidates: TeamPlayerId[];
}};

/** Stable, debounced possession with a staleness flag. */
export interface Possession {
	state: PossessionState;
	/**
	 * True while the belief is being coasted through a vision/contact dropout
	 * (held, but not currently backed by a fresh observation).
	 */
	stale: boolean;
	/**
	 * Set when the ball is being physically contested (see [`BallContest`]).
	 * `None` in the common, uncontested case. Independent of `state`.
	 */
	contest?: BallContest;
}

export interface PostExecutorSettingsBody {
	settings: ExecutorSettings;
}

/** A command from the frontend to the backend. */
export type UiCommand = 
	| { type: "SetManualOverride", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	manual_override: boolean;
}}
	| { type: "OverrideCommand", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	command: PlayerOverrideCommand;
}}
	| { type: "SimulatorCmd", data: SimulatorCmd }
	| { type: "SetPause", data: boolean }
	| { type: "Start",  }
	| { type: "GcCommand", data: GcSimCommand }
	/** Control which teams are active */
	| { type: "SetActiveTeams", data: {
	blue_active: boolean;
	yellow_active: boolean;
}}
	/** Set side assignment */
	| { type: "SetSideAssignment", data: {
	side_assignment: SideAssignment;
}}
	/** Set complete team configuration (for pre-executor setup) */
	| { type: "SetTeamConfiguration", data: {
	configuration: TeamConfiguration;
}}
	/** Swap team colors (Blue <-> Yellow) */
	| { type: "SwapTeamColors",  }
	/** Swap team sides (BlueOnPositive <-> YellowOnPositive) */
	| { type: "SwapTeamSides",  }
	/** Drop a point-of-interest marker at the current live frame (double-space). */
	| { type: "AddMarker", data: {
	label?: string;
}}
	/** Set a single runtime strategy parameter for a team. */
	| { type: "SetStrategyParam", data: {
	team_color: TeamColor;
	key: string;
	value: ParamValue;
}}
	/** Load a recorded log (directory or `.dieslog` zip) for replay. */
	| { type: "LoadLog", data: {
	path: string;
}}
	/** Replay transport controls. */
	| { type: "ReplayPlay",  }
	| { type: "ReplayPause",  }
	| { type: "ReplaySeek", data: {
	t: number;
}}
	| { type: "ReplaySetSpeed", data: {
	speed: number;
}}
	/** Step by a number of frames (negative = backward). Pauses playback. */
	| { type: "ReplayStep", data: {
	delta: number;
}}
	/** Step by a time delta in seconds (negative = backward). Pauses playback. */
	| { type: "ReplayStepTime", data: {
	dt: number;
}}
	/** Direct robot test-bench command (bypasses the executor entirely). */
	| { type: "Bench", data: BenchCommand }
	| { type: "Stop",  };

export interface PostUiCommandBody {
	command: UiCommand;
}

/** The current mode of the UI - either simulation or live. */
export enum UiMode {
	Simulation = "Simulation",
	Live = "Live",
}

export interface PostUiModeBody {
	mode: UiMode;
}

export interface RawGameStateData {
	/** The state of current game */
	game_state: GameState;
	/** The team that is currently performing tasks in the state. */
	operating_team: TeamColor;
	/** The player who performed the freekick (for double touch tracking) */
	freekick_kicker?: TeamPlayerId;
	/**
	 * The robot barred from touching the ball by the double-touch rule: the
	 * restart taker, once the ball is in play AND the taker released it.
	 * Rises later than `freekick_kicker` (which latches at first contact) —
	 * while the taker is still legally taking the kick this is `None`.
	 */
	double_touch_barred?: TeamPlayerId;
	blue_team_max_allowed_bots: number;
	yellow_team_max_allowed_bots: number;
	blue_team_yellow_cards: number;
	yellow_team_yellow_cards: number;
	/** Goals scored, from the referee `TeamInfo` (tracked in sim, real in live). */
	blue_team_score: number;
	yellow_team_score: number;
	blue_team_keeper_id?: PlayerId;
	yellow_team_keeper_id?: PlayerId;
	/** The coarse game stage, e.g. "First half" (display string). */
	stage?: string;
	/** Seconds left in the current stage (can be negative). Interpolated. */
	stage_time_left?: number;
	/**
	 * Seconds remaining for the current action — free kick / placement /
	 * kickoff countdown (can be negative). Interpolated frame-by-frame.
	 */
	action_time_remaining?: number;
	/**
	 * The command that will resume play after the current stoppage ("what's
	 * next"), as a display string.
	 */
	next_command?: string;
	/**
	 * Machine-usable prediction derived from the `next_command` hint: the
	 * `GameState` that will resume play, for the meaningful set-piece restarts
	 * (free kick / kickoff / penalty). `None` otherwise.
	 */
	predicted_next_game_state?: GameState;
	/** The team the predicted restart is for (from the `next_command` color). */
	predicted_operating_team?: TeamColor;
	/** A human-readable reason for the current stoppage, if provided. */
	status_message?: string;
	/** GC-reported team names, if the operator has entered them. */
	blue_team_name?: string;
	yellow_team_name?: string;
}

/** A user point-of-interest marker, surfaced to the replay scrubber. */
export interface ReplayMarker {
	frame_id: number;
	t: number;
	label?: string;
}

/** State of the replay player, pushed to the frontend on change. */
export interface ReplayState {
	loaded: boolean;
	playing: boolean;
	speed: number;
	t_min: number;
	t_max: number;
	current_t: number;
	current_frame_id: number;
	frame_count: number;
	/**
	 * Nominal per-frame timestep in seconds (median of frame deltas), for the
	 * scrubber's frame/fps readout. Zero for degenerate single-frame logs.
	 */
	dt: number;
	markers: ReplayMarker[];
}

export interface SaveSnapshotBody {
	name: string;
	snapshot: FieldSnapshot;
}

/**
 * A captured settings configuration with provenance. `kind` is a free-form
 * tag: `"edit"` (debounced auto-snapshot of a live edit), `"baseline"` (the
 * user-declared known-good config), or `"revert"`.
 */
export interface SettingsSnapshot {
	/** Unix epoch milliseconds. */
	ts: number;
	kind: string;
	settings: ExecutorSettings;
}

export interface SettingsSnapshotsResponse {
	/** The current known-good config, or null if none has been marked yet. */
	baseline?: SettingsSnapshot;
	/** Auto-captured history, newest first. */
	history: SettingsSnapshot[];
}

export interface SnapshotsResponse {
	/** Stored snapshot names, sorted. */
	names: string[];
}

/**
 * The set of runnable binaries the strategy picker can assign to a team.
 * `strategies` are full strategy crates (e.g. `concerto`); `scenarios`
 * are skill-test binaries from the `scenarios` crate (e.g. `handle_ball`).
 * Both are launched the same way — they're just `Strategy` binaries.
 */
export interface StrategiesResponse {
	strategies: string[];
	scenarios: string[];
}

/** A struct to store the world state from a single frame. */
export interface TeamData {
	/**
	 * Timestamp of the frame, in seconds. This timestamp is relative to the time the
	 * world tracking was started.
	 */
	t_received: number;
	/**
	 * Recording timestamp of the frame, in seconds, as reported by vision. This
	 * timestamp is relative to the time the first image was captured.
	 */
	t_capture: number;
	/** The time since the last frame was received, in seconds */
	dt: number;
	own_players: PlayerData[];
	opp_players: PlayerData[];
	/**
	 * Own-color robots on the field that are not assignable roster members
	 * (radio lost, or card-removed — see [`SidelineReason`]). Excluded from
	 * `own_players` so the strategy never roles them, but still avoided as
	 * obstacles by the executor and blocking for ray/radius queries.
	 */
	sidelined_players?: PlayerData[];
	ball?: BallData;
	field_geom?: FieldGeometry;
	current_game_state: GameStateData;
	ball_on_our_side?: Duration;
	ball_on_opp_side?: Duration;
	kicked_ball?: AutorefKickedBallTeam;
	/**
	 * Unified possession metric (absolute / team-tagged — the same value as on
	 * `WorldData`). Converted to a team-relative view at the strategy boundary.
	 */
	possession: Possession;
}

/** The current status of the executor. */
export type ExecutorStatus = 
	| { type: "None",  }
	| { type: "RunningExecutor",  }
	| { type: "Failed", data: string };

/** The current status of the UI. */
export interface UiStatus {
	is_live_available: boolean;
	ui_mode: UiMode;
	executor: ExecutorStatus;
}

export interface WorldData {
	/**
	 * Timestamp of the frame, in seconds. This timestamp is relative to the time the
	 * world tracking was started.
	 */
	t_received: number;
	/**
	 * Recording timestamp of the frame, in seconds, as reported by vision. This
	 * timestamp is relative to the time the first image was captured.
	 */
	t_capture: number;
	/** The time since the last frame was received, in seconds */
	dt: number;
	blue_team: PlayerData[];
	yellow_team: PlayerData[];
	ball?: BallData;
	field_geom?: FieldGeometry;
	game_state: RawGameStateData;
	side_assignment: SideAssignment;
	ball_on_blue_side?: Duration;
	ball_on_yellow_side?: Duration;
	autoref_info?: AutorefInfo;
	/**
	 * Unified ball-possession metric (absolute / team-tagged). Computed once in
	 * the world tracker; the single source of truth for who has the ball.
	 */
	possession: Possession;
}

export interface WorldUpdate {
	world_data: WorldData;
	/**
	 * Monotonic id of this world frame (minted by the executor). Exposed to the
	 * UI for the frame counter and used as the join key in recorded logs.
	 */
	frame_id: number;
	/**
	 * Announcer feed items minted since the previous broadcast. The UI
	 * accumulates these into a scrolling commentary log (deduped by `id`).
	 * Empty on most frames; only populated when something happens.
	 */
	announcements?: Announcement[];
}

/**
 * A command from the bench UI, sent straight to the basestation (no executor,
 * no vision). Robots are addressed by raw robot id.
 */
export type BenchCommand = 
	/** Continuously-streamed motion setpoint for a taken robot. */
	| { type: "SetMotion", data: {
	robot_id: number;
	mode: BenchMotionMode;
	vx: number;
	vy: number;
	/** `w` \[rad/s] in Local mode, heading setpoint \[rad] in Global mode. */
	w_or_heading: number;
	dribble_speed: number;
}}
	/** Zero a single robot's setpoint. */
	| { type: "Stop", data: {
	robot_id: number;
}}
	/** Zero every robot and release control. */
	| { type: "StopAll",  }
	/** Take or release streaming control of a robot. */
	| { type: "TakeControl", data: {
	robot_id: number;
	taken: boolean;
}}
	/** Fire a one-shot action at a single robot. */
	| { type: "OneShot", data: {
	robot_id: number;
	kind: BenchOneShot;
}}
	/**
	 * Set (or clear, with `None`) a continuously-held command that is re-sent to
	 * the robot every stream tick until cleared. Only one-shots that map to a
	 * `RobotCmd` (Arm/ArmReflex/Coast/Discharge/...) are holdable; others are
	 * ignored. Works whether or not the robot is taken for driving.
	 */
	| { type: "SetHold", data: {
	robot_id: number;
	kind?: BenchOneShot;
}}
	/**
	 * Set the raw kick duration (`kick_time_i`, u16 ms) stamped onto every
	 * streamed packet for a robot, so a held reflex-arm carries kick strength.
	 */
	| { type: "SetKickTime", data: {
	robot_id: number;
	kick_time: number;
}}
	/**
	 * Set a continuously-held dribble speed that is streamed even when the
	 * robot isn't taken for driving. `speed` is the raw dribbler value
	 * (0-1000). Send `None` to clear the hold.
	 */
	| { type: "SetDribble", data: {
	robot_id: number;
	speed?: number;
}}
	/** Broadcast a one-shot action to all robots. */
	| { type: "Broadcast", data: {
	kind: BenchOneShot;
}}
	/** Set the radio channel of the base (`robot_id = None`) or a robot. */
	| { type: "SetChannel", data: {
	robot_id?: number;
	channel: number;
}}
	/**
	 * Set the rate (Hz) at which streamed setpoints / the stress-test
	 * keepalive are sent to robots. Clamped backend-side to a sane range.
	 */
	| { type: "SetStreamRate", data: {
	hz: number;
}}
	/**
	 * Enable/disable the radio-link stress test: while active, a benign
	 * zero-motion keepalive is streamed to every online robot at the current
	 * stream rate, purely to load the link so its feedback rate can be
	 * observed under stress.
	 */
	| { type: "SetStress", data: {
	active: boolean;
}};

/** Motion frame for a bench `SetMotion` command. */
export enum BenchMotionMode {
	/** `(vx, vy)` in the robot's local frame, `w_or_heading` is `w` \[rad/s]. */
	Local = "Local",
	/** `(vx, vy)` in the global frame, `w_or_heading` is the heading setpoint \[rad]. */
	Global = "Global",
}

/** A one-shot bench action targeting a single robot (or broadcast). */
export type BenchOneShot = 
	| { type: "Beep",  }
	| { type: "Reboot",  }
	| { type: "Shutdown",  }
	| { type: "Coast",  }
	| { type: "Arm",  }
	| { type: "Disarm",  }
	| { type: "Discharge",  }
	/**
	 * Fire the kicker. `kick_time` is the raw firmware kick duration
	 * (`GenericCommand.kick_time_i`, a `u16` in milliseconds) sent verbatim.
	 */
	| { type: "Kick", data: {
	kick_time: number;
}}
	| { type: "ArmReflex",  }
	| { type: "CalibrateBreakbeam",  }
	| { type: "CalibrateImu",  }
	| { type: "GetVersion",  }
	| { type: "ZeroHeading",  }
	| { type: "SetHeading", data: {
	angle: number;
}};

export enum DebugColor {
	Red = "red",
	Green = "green",
	Orange = "orange",
	Purple = "purple",
	Blue = "blue",
	Gray = "gray",
}

export type DebugShape = 
	| { type: "Cross", data: {
	center: Vector2;
	color: DebugColor;
}}
	/**
	 * A semantic marker drawn with a distinct glyph, optionally tethered to its
	 * owning robot in the UI.
	 */
	| { type: "Marker", data: {
	kind: MarkerKind;
	center: Vector2;
	color: DebugColor;
	owner?: PlayerId;
}}
	| { type: "Circle", data: {
	center: Vector2;
	radius: number;
	fill?: DebugColor;
	stroke?: DebugColor;
}}
	| { type: "Line", data: {
	start: Vector2;
	end: Vector2;
	color: DebugColor;
}}
	| { type: "TreeNode", data: {
	name: string;
	id: string;
	children_ids: string[];
	is_active: boolean;
	node_type: string;
	internal_state?: string;
	additional_info?: string;
}};

export type GcSimCommand = 
	| { type: "Stop",  }
	| { type: "Halt",  }
	| { type: "NormalStart",  }
	| { type: "ForceStart",  }
	| { type: "KickOff", data: {
	team_color: TeamColor;
}}
	| { type: "Penalty", data: {
	team_color: TeamColor;
}}
	| { type: "DirectFree", data: {
	team_color: TeamColor;
}}
	| { type: "BallPlacement", data: {
	team_color: TeamColor;
	position: Vector2;
}}
	/** Show a yellow card to a team (lowers its `max_allowed_bots` for 120 s). */
	| { type: "YellowCard", data: {
	team_color: TeamColor;
}};

/** Semantic kind of a [`DebugShape::Marker`], controlling which glyph the UI draws. */
export enum MarkerKind {
	/** A robot's final destination. */
	Target = "target",
	/** An intermediate point along a path. */
	Waypoint = "waypoint",
	/** A kick / shot aim point. */
	KickTarget = "kick_target",
}

/** An override command for a player for manual control. */
export type PlayerOverrideCommand = 
	/** Do nothing */
	| { type: "Stop",  }
	/** Move the robot to a globel position and yaw */
	| { type: "MoveTo", data: {
	position: Vector2;
	yaw?: Angle;
	/** Dribbler speed normalised to \[0, 1\] */
	dribble_speed: number;
	arm_kick: boolean;
}}
	/** Move the robot with velocity in local frame */
	| { type: "LocalVelocity", data: {
	velocity: Vector2;
	yaw?: Angle;
	/** Dribbler speed normalised to \[0, 1\] */
	dribble_speed: number;
	arm_kick: boolean;
}}
	/** Move the robot with velocity in global frame */
	| { type: "GlobalVelocity", data: {
	velocity: Vector2;
	yaw?: Angle;
	/** Dribbler speed normalised to \[0, 1\] */
	dribble_speed: number;
	arm_kick: boolean;
}}
	/** Engage the kicker */
	| { type: "Kick", data: {
	speed: number;
}}
	/** Discharge the kicker safely */
	| { type: "DischargeKicker",  }
	| { type: "SetFanSpeed", data: {
	speed: number;
}};

/** Role of a player according to the game rules. These are mainly for rule-compliance. */
export enum RoleType {
	/** A regular player with no special role */
	Player = "Player",
	/** The goalkeeper */
	Goalkeeper = "Goalkeeper",
	/** The attacking kicker during kick-off */
	KickoffKicker = "KickoffKicker",
	/** penalty kicker */
	PenaltyKicker = "PenaltyKicker",
	/** freekicker */
	FreeKicker = "FreeKicker",
	Waller = "Waller",
	/**
	 * Robot posed in a static logo/warmup formation (triangle). Exempt from the
	 * stop-state speed clamp (except Halt) so it may slowly reposition.
	 */
	Formation = "Formation",
}

/** Command to modify the simulator state. */
export type SimulatorCmd = 
	| { type: "ApplyBallForce", data: {
	force: Vector2;
}}
	| { type: "TeleportBall", data: {
	position: Vector2;
}}
	| { type: "TeleportRobot", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	position: Vector2;
	yaw: Angle;
}}
	| { type: "AddRobot", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	position: Vector2;
	yaw: Angle;
}}
	| { type: "RemoveRobot", data: {
	team_color: TeamColor;
	player_id: PlayerId;
}};

export type UiWorldState = 
	| { type: "Loaded", data: WorldData }
	| { type: "None",  };

/** WebSocket message types sent from backend to frontend */
export type WsMessage = 
	/**
	 * Carries the full `WorldUpdate` (world data + frame id) so the frontend can
	 * show the current frame number for both live and replay.
	 */
	| { type: "WorldUpdate", data: WorldUpdate }
	| { type: "Debug", data: DebugMap }
	| { type: "ReplayState", data: ReplayState }
	| { type: "ConsoleLog", data: ConsoleLogMessage };


export type Vector2 = [number, number];
export type Vector3 = [number, number, number];
export type Duration = number;
export type HashSet<T> = Array<T>;
export type ParamValue =
  | { Bool: boolean }
  | { Float: number }
  | { Int: number }
  | { Text: string };
