/*
 Generated by typeshare 1.13.3
*/

/**
 * An angle in radians, always in (-pi, pi]. This type supports safe arithmetic
 * operations:
 * 
 * ```ignore
 * # use dies_core::Angle;
 * let a = Angle::from_degrees(90.0);
 * let b = Angle::from_degrees(45.0);
 * let c = a + b;
 * assert_eq!(c.degrees(), 135.0);
 * ```
 */
export type Angle = number;

export type DebugValue = 
	| { type: "Shape", data: DebugShape }
	| { type: "Number", data: number }
	| { type: "String", data: string };

/**
 * A map of debug messages.
 * 
 * # Key format
 * 
 * The keys should always be `snake_case` and should only contain alphanumerical
 * characters. The `.` character is reserved for separating different parts of the key.
 * 
 * Keys can be arbitrary, but there are some patterns that are recognized by the
 * UI:
 * - `p{player_id}.{value}`: A value associated with a player.
 */
export type DebugMap = Record<string, DebugValue>;

export type PlayerId = number;

export interface AutorefKickedBall {
	/** The initial position [m] from which the ball was kicked */
	pos: Vector2;
	/** The initial velocity [m/s] with which the ball was kicked */
	vel: Vector3;
	/** The unix timestamp [s] when the kick was performed */
	start_timestamp: number;
	/** The predicted unix timestamp [s] when the ball comes to a stop */
	stop_timestamp?: number;
	/** The predicted position [m] at which the ball will come to a stop */
	stop_pos?: Vector2;
}

export interface AutorefInfo {
	kicked_ball?: AutorefKickedBall;
}

export interface AutorefKickedBallTeam {
	/** The initial position [m] from which the ball was kicked */
	pos: Vector2;
	/** The initial velocity [m/s] with which the ball was kicked */
	vel: Vector3;
	/** The unix timestamp [s] when the kick was performed */
	start_timestamp: number;
	/** The predicted unix timestamp [s] when the ball comes to a stop */
	stop_timestamp?: number;
	/** The predicted position [m] at which the ball will come to a stop */
	stop_pos?: Vector2;
	/** The robot that kicked the ball */
	robot_id: PlayerId;
	we_kicked: boolean;
}

/**
 * Tuning for the two-layer collision-avoidance stack (global planner + ORCA)
 * and the shared obstacle model they both read.
 * 
 * All distances are millimetres, times are seconds. A single `AvoidanceConfig`
 * is shared across the whole team and applied live from settings updates.
 */
export interface AvoidanceConfig {
	/**
	 * ORCA's emergency margin on top of the two-robot contact distance [mm].
	 * ORCA is a last-resort reactive backstop, so keep this small (≈0) — the
	 * planner does the real avoidance with `planner_margin`. The planner inflates
	 * robots by `robot_clearance + planner_margin`; ORCA only by this.
	 */
	robot_clearance: number;
	/** Inset of the robot centre from the physical field walls [mm]. */
	wall_margin: number;
	/** Keep-out margin grown around each defense area [mm]. */
	defense_margin: number;
	/** Ball keep-out radius during `Stop` [mm] (rule: stay 500 mm clear). */
	ball_stop_radius: number;
	/** Base ball keep-out radius when `avoid_ball` is set [mm]. */
	ball_base_radius: number;
	/** Additional ball keep-out radius scaled by `avoid_ball_care` [mm]. */
	ball_care_scale: number;
	/** How far ahead moving robots are extrapolated at constant velocity [s]. */
	robot_extrapolation: number;
	/**
	 * ORCA time horizon τ [s]: how far ahead reciprocal collisions are
	 * resolved. Kept short so ORCA only fires for imminent collisions, not in
	 * normal play (planned avoidance handles the rest).
	 */
	time_horizon: number;
	/**
	 * Speed below which a robot counts as "stationary" for reciprocity gating
	 * [mm/s]. A stationary robot does not yield to a moving one — the mover
	 * takes the full avoidance burden.
	 */
	stationary_speed: number;
	/**
	 * Prefer steering around obstacles over braking for them: drop ORCA's
	 * cut-off-circle projection so a constrained velocity is deflected (turned)
	 * rather than slowed. Avoids the "sticky crawl" where ORCA suppresses speed
	 * near an obstacle. Falls back to the 3-D LP when genuinely boxed in.
	 */
	prefer_steering: boolean;
	/** Only robots within this distance are considered ORCA neighbours [mm]. */
	neighbor_dist: number;
	/** Cap on the number of neighbours folded into a single ORCA LP. */
	max_neighbors: number;
	/** Grid cell size for the planner's any-angle search [mm]. */
	grid_resolution: number;
	/**
	 * The planner's robot-avoidance margin [mm]: it routes paths clear of
	 * robots by `robot_clearance + planner_margin`. This is the primary
	 * avoidance — keep it comfortable so ORCA rarely needs to engage.
	 */
	planner_margin: number;
	/**
	 * Replan only when the target has moved more than this [mm] (hysteresis to
	 * suppress path flicker).
	 */
	replan_target_tol: number;
	/**
	 * Run the global path planner. When false, the follower steers straight at
	 * the target and only ORCA provides avoidance.
	 */
	planner_enabled: boolean;
	/**
	 * Run ORCA reciprocal avoidance. When false, the path-follower velocity
	 * passes through untouched (useful for isolating layers when debugging).
	 */
	orca_enabled: boolean;
}

/** A struct to store the ball state from a single frame. */
export interface BallData {
	/**
	 * Unix timestamp of the recorded frame from which this data was extracted (in
	 * seconds). This is the time that ssl-vision received the frame.
	 */
	timestamp: number;
	/** Position of the ball filtered by us, in mm, in dies coordinates */
	position: Vector3;
	/** Raw position as reported by vision */
	raw_position: Vector3[];
	/** Velocity of the ball in mm/s, in dies coordinates */
	velocity: Vector3;
	/** Whether the ball is being detected */
	detected: boolean;
}

/** The status of a sub-system on the robot */
export enum SysStatus {
	Emergency = "Emergency",
	Ok = "Ok",
	Ready = "Ready",
	Stop = "Stop",
	Starting = "Starting",
	Overtemp = "Overtemp",
	NoReply = "NoReply",
	Armed = "Armed",
	Disarmed = "Disarmed",
	Safe = "Safe",
	NotInstalled = "NotInstalled",
	Standby = "Standby",
}

/** A message from one of our robots to the AI */
export interface PlayerFeedbackMsg {
	/** The robot's ID */
	id: PlayerId;
	primary_status?: SysStatus;
	kicker_status?: SysStatus;
	imu_status?: SysStatus;
	fan_status?: SysStatus;
	kicker_cap_voltage?: number;
	kicker_temp?: number;
	motor_statuses?: [SysStatus, SysStatus, SysStatus, SysStatus, SysStatus];
	motor_speeds?: [number, number, number, number, number];
	motor_temps?: [number, number, number, number, number];
	breakbeam_ball_detected?: boolean;
	breakbeam_sensor_ok?: boolean;
	pack_voltages?: [number, number];
}

export interface BasestationResponse {
	blue_team: PlayerFeedbackMsg[];
	yellow_team: PlayerFeedbackMsg[];
	unknown_team: PlayerFeedbackMsg[];
}

/**
 * Settings for the low-level controller.
 * 
 * Every field here is consumed by `PlayerController` or one of its
 * subcontrollers (`PathFollower`, `YawController`).
 * Low-level controller limits and path-follower tuning. The translational path
 * follower (`PathFollower`) produces a speed profile (cruise / cornering /
 * braking-to-goal) and the player controller applies a first-order asymmetric
 * acceleration clamp; `YawController` handles heading.
 */
export interface ControllerSettings {
	/** Acceleration cap when speeding up (mm/s²). */
	max_acceleration: number;
	/**
	 * Deceleration cap when slowing down (mm/s²); also the braking authority the
	 * follower's speed profile plans against.
	 */
	max_deceleration: number;
	/** Speed cap on the commanded velocity magnitude (mm/s). */
	max_velocity: number;
	/**
	 * Lateral (cornering) acceleration cap (mm/s²) — sets how fast the robot may
	 * carry through a path corner.
	 */
	lateral_acceleration: number;
	/**
	 * Proportional arrival gain (1/s): commanded speed eases off as `kp ×
	 * remaining distance` into corners and the goal. Over-damped (no overshoot);
	 * lower = gentler/earlier braking, higher = later/snappier.
	 */
	approach_kp: number;
	/** Minimum pure-pursuit lookahead distance (mm), used at low speed. */
	lookahead_min: number;
	/** Pure-pursuit lookahead time (s): lookahead = clamp(time·speed, min, max). */
	lookahead_time: number;
	/** Maximum angular velocity (rad/s). */
	max_angular_velocity: number;
	/**
	 * Maximum angular acceleration (rad/s²) — passed to YawController as the
	 * upper bound on its planned angular accel.
	 */
	max_angular_acceleration: number;
	/** Proportional gain for heading tracking. */
	angle_kp: number;
	/** Heading deadzone (rad) — yaw control outputs zero inside this band. */
	angle_cutoff_distance: number;
}

/**
 * # Team-Specific Coordinate System
 * 
 * This module provides coordinate system transformations to create a consistent
 * team-specific reference frame where the +x axis always points towards the
 * enemy goal, regardless of which side of the field the team is defending.
 * 
 * ## Coordinate System Philosophy
 * 
 * In RoboCup SSL, teams can be assigned to defend either the positive or negative
 * x side of the field. To simplify strategy code, we transform all coordinates
 * into a team-specific coordinate system where:
 * 
 * - **+x axis**: Always points towards the enemy goal (attacking direction)
 * - **-x axis**: Always points towards our own goal (defending direction)
 * - **y axis**: Remains unchanged (left/right from team perspective)
 * 
 * ## How It Works
 * 
 * The transformation is based on two key pieces of information:
 * 1. **SideAssignment**: Which team (Blue/Yellow) defends the positive x side
 * 2. **TeamColor**: The color of our team (Blue/Yellow)
 * 
 * ### Transformation Rules
 * 
 * - If our team attacks in the same direction as world +x: coordinates remain unchanged
 * - If our team attacks in the opposite direction: x coordinates are negated, angles are mirrored
 */
export enum TeamColor {
	Blue = "Blue",
	Yellow = "Yellow",
}

export interface TeamPlayerId {
	team_color: TeamColor;
	player_id: PlayerId;
}

/** Runtime information about the active executor. */
export interface ExecutorInfo {
	/** Whether the executor is currently paused. */
	paused: boolean;
	/** The player IDs that are currently controlled manually. */
	manual_controlled_players: TeamPlayerId[];
	/** Which teams are currently active/controlled. */
	active_teams: TeamColor[];
}

/** Runtime information about the active executor. */
export interface ExecutorInfoResponse {
	info?: ExecutorInfo;
}

/** A field mask for the `WorldTracker`. */
export interface FieldMask {
	x_min: number;
	x_max: number;
	y_min: number;
	y_max: number;
}

/**
 * Settings for the `WorldTracker`.
 * 
 * Kalman variances are unit-time process noise (`*_unit_transition_var`,
 * in mm²/s for the constant-velocity model) and measurement variance
 * (`*_measurement_var`, in mm²). Higher transition variance → tracker
 * trusts measurements more (snappier, noisier). Higher measurement
 * variance → tracker trusts dynamics model more (smoother, laggier).
 */
export interface TrackerSettings {
	/**
	 * Vision crop applied at the ball tracker — fractions of the field
	 * half-extent. Defaults to the full field.
	 */
	field_mask: FieldMask;
	/**
	 * Constant-velocity process noise (white-noise *acceleration* PSD). Used when
	 * `player_use_acceleration` is false.
	 */
	player_unit_transition_var: number;
	/**
	 * Constant-acceleration process noise (white-noise *jerk* PSD). Used when
	 * `player_use_acceleration` is true. On a totally different numeric scale from
	 * the CV value, which is why it is a separate field — toggling the model must
	 * not silently leave the wrong process-noise magnitude in place.
	 */
	player_ca_unit_transition_var: number;
	/**
	 * Measurement noise for the player position Kalman filter (mm²). Should match
	 * the real vision noise floor (~0.4 mm² measured on hardware).
	 */
	player_measurement_var: number;
	/**
	 * Use a constant-acceleration motion model (state x,vx,ax,…) for players
	 * instead of constant-velocity. The CA model anticipates sustained
	 * acceleration, cutting the onset/transient velocity lag in hard maneuvers.
	 */
	player_use_acceleration: boolean;
	/**
	 * Feed the commanded velocity into the filter's predict step as a first-order
	 * lag toward the setpoint (feedforward). Reduces lag further during commanded
	 * maneuvers. EXPERIMENTAL — needs field tuning of `player_command_tau`.
	 */
	player_use_command_feedforward?: boolean;
	/**
	 * First-order time constant (s) for command feedforward: the predicted velocity
	 * relaxes toward the commanded velocity with this τ. ~robot velocity-loop
	 * response time. Only used when `player_use_command_feedforward` is true.
	 */
	player_command_tau: number;
	/**
	 * EWMA factor for the player yaw low-pass filter — 0 = no filtering,
	 * 1 = freeze.
	 */
	player_yaw_lpf_alpha: number;
	/** Process noise for the ball position/velocity Kalman filter (mm²/s). */
	ball_unit_transition_var: number;
	/** Measurement noise for the ball position Kalman filter (mm²). */
	ball_measurement_var: number;
}

/**
 * Represents which team defends the positive x side of the field.
 * 
 * In RoboCup SSL, the field coordinate system is fixed, but teams can be
 * assigned to defend either side. This enum tracks that assignment.
 */
export enum SideAssignment {
	/** Blue team defends the positive x side (+x goal) */
	BlueOnPositive = "BlueOnPositive",
	/** Yellow team defends the positive x side (+x goal) */
	YellowOnPositive = "YellowOnPositive",
}

/** Team configuration that can be set before executor creation. */
export interface TeamConfiguration {
	/** Whether the blue team is active */
	blue_active: boolean;
	/** Whether the yellow team is active */
	yellow_active: boolean;
	/** Which team defends the positive x side */
	side_assignment: SideAssignment;
	/** IPC strategy binary name for blue team (None = no strategy) */
	blue_strategy?: string;
	/** IPC strategy binary name for yellow team (None = no strategy) */
	yellow_strategy?: string;
}

export enum Handicap {
	NoKicker = "no_kicker",
	NoDribbler = "no_dribbler",
	NoBreakbeam = "no_breakbeam",
}

export interface TeamSpecificSettings {
	handicaps: Record<PlayerId, Handicap[]>;
}

export interface SkillSettings {
	dribbler_radius_near_center: number;
	dribbler_radius_far_center: number;
	dribbler_radius_breakbeam_factor: number;
	fetch_ball_preshoot_offset: number;
	fetch_ball_preshoot_ball_avoidance: number;
}

/** Settings for the executor. */
export interface ExecutorSettings {
	controller_settings: ControllerSettings;
	tracker_settings: TrackerSettings;
	team_configuration: TeamConfiguration;
	yellow_team_settings: TeamSpecificSettings;
	blue_team_settings: TeamSpecificSettings;
	skill_settings: SkillSettings;
	allow_no_vision: boolean;
	/**
	 * Global on/off for goal-area avoidance. When false, both compliance and
	 * the controller skip the goal-area keep-out logic (goalkeeper exception
	 * is irrelevant since the whole feature is off).
	 */
	goal_area_avoidance: boolean;
	/**
	 * Collision-avoidance tuning (obstacle margins + global planner + ORCA).
	 * Applied live to the planner and ORCA solver.
	 */
	avoidance?: AvoidanceConfig;
}

export interface ExecutorSettingsResponse {
	settings: ExecutorSettings;
}

/** A single field arc -- eg. the center circle */
export interface FieldCircularArc {
	/** Readable name of the arc */
	name: string;
	/** Center of the arc, in dies coordinates */
	center: Vector2;
	radius: number;
	a1: number;
	a2: number;
	thickness: number;
}

/** A single field line segment */
export interface FieldLineSegment {
	/** Readable name of the line segment */
	name: string;
	/** Start Vector2 of the line segment, in dies coordinates */
	p1: Vector2;
	/** End Vector2 of the line segment, in dies coordinates */
	p2: Vector2;
	/** Thickness of the line segment, in mm */
	thickness: number;
}

/** The field geometry. */
export interface FieldGeometry {
	/** Field length (distance between goal lines) in mm */
	field_length: number;
	/** Field width (distance between touch lines) in mm */
	field_width: number;
	/** Goal width (distance inner edges of goal posts) in mm */
	goal_width: number;
	/** Goal depth (distance from outer goal line edge to inner goal back) in mm */
	goal_depth: number;
	/** Boundary width (distance from touch/goal line centers to boundary walls) in mm */
	boundary_width: number;
	/** Generated line segments based on the other parameters */
	line_segments: FieldLineSegment[];
	/** Generated circular arcs based on the other parameters */
	circular_arcs: FieldCircularArc[];
	/** Penalty area depth (distance from goal line to penalty mark) in mm */
	penalty_area_depth: number;
	/** Penalty area width (distance from penalty mark to penalty area edge) in mm */
	penalty_area_width: number;
	/** Center circle radius in mm */
	center_circle_radius: number;
	/** Distance from goal line to penalty mark in mm */
	goal_line_to_penalty_mark: number;
	/** Ball radius in mm */
	ball_radius: number;
}

/** The game state, as reported by the referee. */
export type GameState = 
	| { type: "Unknown",  }
	| { type: "Halt",  }
	| { type: "Timeout",  }
	| { type: "Stop",  }
	| { type: "PrepareKickoff",  }
	| { type: "BallReplacement", data: Vector2 }
	| { type: "PreparePenalty",  }
	| { type: "Kickoff",  }
	| { type: "FreeKick",  }
	| { type: "Penalty",  }
	| { type: "PenaltyRun",  }
	| { type: "Run",  };

export interface GameStateData {
	/** The state of current game */
	game_state: GameState;
	/**
	 * If we are the main party currently performing tasks in the state.
	 * true for symmetric states(halt stop run timout)
	 */
	us_operating: boolean;
	yellow_cards: number;
	/**
	 * The player who performed the freekick, if it was us (for double touch tracking)
	 * Only Some until another player touches the ball
	 */
	freekick_kicker?: PlayerId;
	max_allowed_bots: number;
	our_keeper_id?: PlayerId;
}

export interface GetDebugMapResponse {
	debug_map: DebugMap;
}

/** A recorded log available for replay (directory or `.dieslog` zip). */
export interface LogInfo {
	name: string;
	path: string;
	session_start_unix: number;
	duration_s?: number;
	end_unix?: number;
	frame_count: number;
	is_simulation: boolean;
	blue_strategy?: string;
	yellow_strategy?: string;
	is_zip: boolean;
}

export interface LogsResponse {
	logs: LogInfo[];
}

/** A struct to store the player state from a single frame. */
export interface PlayerData {
	/**
	 * Unix timestamp of the recorded frame from which this data was extracted (in
	 * seconds). This is the time that ssl-vision received the frame.
	 */
	timestamp: number;
	/** The player's unique id */
	id: PlayerId;
	/** Unfiltered position as reported by vision */
	raw_position: Vector2;
	/** Position of the player filtered by us in mm, in dies coordinates */
	position: Vector2;
	/** Velocity of the player in mm/s, in dies coordinates */
	velocity: Vector2;
	/**
	 * Yaw of the player, in radians, (`-pi`, `pi`), where `0` is the positive
	 * x direction, and `pi/2` is the positive y direction.
	 */
	yaw: Angle;
	/** Unfiltered yaw as reported by vision */
	raw_yaw: Angle;
	/** Angular speed of the player (in rad/s) */
	angular_speed: number;
	/**
	 * EWMA-smoothed position noise floor in mm — RMS of the Kalman innovation
	 * (raw vision vs. constant-velocity prediction). Useful for diagnosing
	 * whether downstream controllers are tracking sensor noise.
	 */
	position_noise: number;
	/** The overall status of the robot. Only available for own players. */
	primary_status?: SysStatus;
	/** The voltage of the kicker capacitor (in V). Only available for own players. */
	kicker_cap_voltage?: number;
	/** The temperature of the kicker. Only available for own players. */
	kicker_temp?: number;
	/** The voltages of the battery packs. Only available for own players. */
	pack_voltages?: [number, number];
	/** Whether the breakbeam sensor detected a ball. Only available for own players. */
	breakbeam_ball_detected: boolean;
	imu_status?: SysStatus;
	kicker_status?: SysStatus;
	handicaps: HashSet<Handicap>;
}

export interface PostExecutorSettingsBody {
	settings: ExecutorSettings;
}

/** A command from the frontend to the backend. */
export type UiCommand = 
	| { type: "SetManualOverride", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	manual_override: boolean;
}}
	| { type: "OverrideCommand", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	command: PlayerOverrideCommand;
}}
	| { type: "SimulatorCmd", data: SimulatorCmd }
	| { type: "SetPause", data: boolean }
	| { type: "Start",  }
	| { type: "GcCommand", data: GcSimCommand }
	/** Control which teams are active */
	| { type: "SetActiveTeams", data: {
	blue_active: boolean;
	yellow_active: boolean;
}}
	/** Set side assignment */
	| { type: "SetSideAssignment", data: {
	side_assignment: SideAssignment;
}}
	/** Set complete team configuration (for pre-executor setup) */
	| { type: "SetTeamConfiguration", data: {
	configuration: TeamConfiguration;
}}
	/** Swap team colors (Blue <-> Yellow) */
	| { type: "SwapTeamColors",  }
	/** Swap team sides (BlueOnPositive <-> YellowOnPositive) */
	| { type: "SwapTeamSides",  }
	/** Load and start a JS scenario by file name (resolved against `scenarios/`). */
	| { type: "StartScenario", data: {
	scenario: string;
	team?: TeamColor;
}}
	/** Stop the currently running scenario and return to strategy mode. */
	| { type: "StopScenario",  }
	/** Drop a point-of-interest marker at the current live frame (double-space). */
	| { type: "AddMarker", data: {
	label?: string;
}}
	/** Load a recorded log (directory or `.dieslog` zip) for replay. */
	| { type: "LoadLog", data: {
	path: string;
}}
	/** Replay transport controls. */
	| { type: "ReplayPlay",  }
	| { type: "ReplayPause",  }
	| { type: "ReplaySeek", data: {
	t: number;
}}
	| { type: "ReplaySetSpeed", data: {
	speed: number;
}}
	| { type: "Stop",  };

export interface PostUiCommandBody {
	command: UiCommand;
}

/** The current mode of the UI - either simulation or live. */
export enum UiMode {
	Simulation = "Simulation",
	Live = "Live",
}

export interface PostUiModeBody {
	mode: UiMode;
}

export interface RawGameStateData {
	/** The state of current game */
	game_state: GameState;
	/** The team that is currently performing tasks in the state. */
	operating_team: TeamColor;
	/** The player who performed the freekick (for double touch tracking) */
	freekick_kicker?: TeamPlayerId;
	blue_team_max_allowed_bots: number;
	yellow_team_max_allowed_bots: number;
	blue_team_yellow_cards: number;
	yellow_team_yellow_cards: number;
	blue_team_keeper_id?: PlayerId;
	yellow_team_keeper_id?: PlayerId;
}

/** A user point-of-interest marker, surfaced to the replay scrubber. */
export interface ReplayMarker {
	frame_id: number;
	t: number;
	label?: string;
}

/** State of the replay player, pushed to the frontend on change. */
export interface ReplayState {
	loaded: boolean;
	playing: boolean;
	speed: number;
	t_min: number;
	t_max: number;
	current_t: number;
	current_frame_id: number;
	frame_count: number;
	markers: ReplayMarker[];
}

export interface ScenarioArtifact {
	tag: string;
	value_json: string;
}

/** A single scenario file available on disk. */
export interface ScenarioInfo {
	name: string;
	path: string;
}

export type TestStatus = 
	| { state: "Idle",  }
	| { state: "Starting",  }
	| { state: "Running", data: {
	name: string;
}}
	| { state: "Completed", data: {
	artifacts: ScenarioArtifact[];
}}
	| { state: "Failed", data: {
	error: string;
}}
	| { state: "Aborted",  };

export interface ScenariosResponse {
	scenarios: ScenarioInfo[];
	status: TestStatus;
}

/** A struct to store the world state from a single frame. */
export interface TeamData {
	/**
	 * Timestamp of the frame, in seconds. This timestamp is relative to the time the
	 * world tracking was started.
	 */
	t_received: number;
	/**
	 * Recording timestamp of the frame, in seconds, as reported by vision. This
	 * timestamp is relative to the time the first image was captured.
	 */
	t_capture: number;
	/** The time since the last frame was received, in seconds */
	dt: number;
	own_players: PlayerData[];
	opp_players: PlayerData[];
	ball?: BallData;
	field_geom?: FieldGeometry;
	current_game_state: GameStateData;
	ball_on_our_side?: Duration;
	ball_on_opp_side?: Duration;
	kicked_ball?: AutorefKickedBallTeam;
	skill_settings: SkillSettings;
}

export enum TestLogLevel {
	Info = "Info",
	Warn = "Warn",
	Error = "Error",
	Record = "Record",
}

export interface TestLogEntry {
	level: TestLogLevel;
	tag?: string;
	message: string;
	/** Optional structured payload (JSON-serialized). `log.record` uses this. */
	value_json?: string;
	/** Milliseconds since UNIX epoch at emission time. */
	ts_ms: number;
}

/** The current status of the executor. */
export type ExecutorStatus = 
	| { type: "None",  }
	| { type: "RunningExecutor",  }
	| { type: "Failed", data: string };

/** The current status of the UI. */
export interface UiStatus {
	is_live_available: boolean;
	ui_mode: UiMode;
	executor: ExecutorStatus;
}

export interface WorldData {
	/**
	 * Timestamp of the frame, in seconds. This timestamp is relative to the time the
	 * world tracking was started.
	 */
	t_received: number;
	/**
	 * Recording timestamp of the frame, in seconds, as reported by vision. This
	 * timestamp is relative to the time the first image was captured.
	 */
	t_capture: number;
	/** The time since the last frame was received, in seconds */
	dt: number;
	blue_team: PlayerData[];
	yellow_team: PlayerData[];
	ball?: BallData;
	field_geom?: FieldGeometry;
	game_state: RawGameStateData;
	side_assignment: SideAssignment;
	ball_on_blue_side?: Duration;
	ball_on_yellow_side?: Duration;
	autoref_info?: AutorefInfo;
	skill_settings: SkillSettings;
}

export interface WorldUpdate {
	world_data: WorldData;
	/**
	 * Monotonic id of this world frame (minted by the executor). Exposed to the
	 * UI for the frame counter and used as the join key in recorded logs.
	 */
	frame_id: number;
}

export enum DebugColor {
	Red = "red",
	Green = "green",
	Orange = "orange",
	Purple = "purple",
	Blue = "blue",
	Gray = "gray",
}

export type DebugShape = 
	| { type: "Cross", data: {
	center: Vector2;
	color: DebugColor;
}}
	| { type: "Circle", data: {
	center: Vector2;
	radius: number;
	fill?: DebugColor;
	stroke?: DebugColor;
}}
	| { type: "Line", data: {
	start: Vector2;
	end: Vector2;
	color: DebugColor;
}}
	| { type: "TreeNode", data: {
	name: string;
	id: string;
	children_ids: string[];
	is_active: boolean;
	node_type: string;
	internal_state?: string;
	additional_info?: string;
}};

export type GcSimCommand = 
	| { type: "Stop",  }
	| { type: "Halt",  }
	| { type: "NormalStart",  }
	| { type: "ForceStart",  }
	| { type: "KickOff", data: {
	team_color: TeamColor;
}}
	| { type: "Penalty", data: {
	team_color: TeamColor;
}}
	| { type: "DirectFree", data: {
	team_color: TeamColor;
}}
	| { type: "BallPlacement", data: {
	team_color: TeamColor;
	position: Vector2;
}};

/** An override command for a player for manual control. */
export type PlayerOverrideCommand = 
	/** Do nothing */
	| { type: "Stop",  }
	/** Move the robot to a globel position and yaw */
	| { type: "MoveTo", data: {
	position: Vector2;
	yaw?: Angle;
	/** Dribbler speed normalised to \[0, 1\] */
	dribble_speed: number;
	arm_kick: boolean;
}}
	/** Move the robot with velocity in local frame */
	| { type: "LocalVelocity", data: {
	velocity: Vector2;
	yaw?: Angle;
	/** Dribbler speed normalised to \[0, 1\] */
	dribble_speed: number;
	arm_kick: boolean;
}}
	/** Move the robot with velocity in global frame */
	| { type: "GlobalVelocity", data: {
	velocity: Vector2;
	yaw?: Angle;
	/** Dribbler speed normalised to \[0, 1\] */
	dribble_speed: number;
	arm_kick: boolean;
}}
	/** Engage the kicker */
	| { type: "Kick", data: {
	speed: number;
}}
	/** Discharge the kicker safely */
	| { type: "DischargeKicker",  }
	| { type: "SetFanSpeed", data: {
	speed: number;
}};

/** Role of a player according to the game rules. These are mainly for rule-compliance. */
export enum RoleType {
	/** A regular player with no special role */
	Player = "Player",
	/** The goalkeeper */
	Goalkeeper = "Goalkeeper",
	/** The attacking kicker during kick-off */
	KickoffKicker = "KickoffKicker",
	/** penalty kicker */
	PenaltyKicker = "PenaltyKicker",
	/** freekicker */
	FreeKicker = "FreeKicker",
	Waller = "Waller",
}

/** Command to modify the simulator state. */
export type SimulatorCmd = 
	| { type: "ApplyBallForce", data: {
	force: Vector2;
}}
	| { type: "TeleportBall", data: {
	position: Vector2;
}}
	| { type: "TeleportRobot", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	position: Vector2;
	yaw: Angle;
}}
	| { type: "AddRobot", data: {
	team_color: TeamColor;
	player_id: PlayerId;
	position: Vector2;
	yaw: Angle;
}}
	| { type: "RemoveRobot", data: {
	team_color: TeamColor;
	player_id: PlayerId;
}};

export type UiWorldState = 
	| { type: "Loaded", data: WorldData }
	| { type: "None",  };

/** WebSocket message types sent from backend to frontend */
export type WsMessage = 
	/**
	 * Carries the full `WorldUpdate` (world data + frame id) so the frontend can
	 * show the current frame number for both live and replay.
	 */
	| { type: "WorldUpdate", data: WorldUpdate }
	| { type: "Debug", data: DebugMap }
	| { type: "ScenarioLog", data: TestLogEntry }
	| { type: "ScenarioStatus", data: TestStatus }
	| { type: "ReplayState", data: ReplayState };

export type Vector2 = [number, number];
export type Vector3 = [number, number, number];
export type Duration = number;
export type HashSet<T> = Array<T>;
