"""Render the `//`-prefixed doc comment from a Model's equations and exports."""

from __future__ import annotations

import sympy as sp

from .model import Model

HEADER = (
    "// @generated by crates/dies-mpc/codegen/generate.py. DO NOT EDIT.\n"
    "// Manual edits belong in the wrapper modules, not in this generated file.\n"
    "//\n"
    "// Regenerate with:\n"
    "//   uv run --project crates/dies-mpc/codegen python crates/dies-mpc/codegen/generate.py\n"
    "//\n"
    "#![allow(clippy::type_complexity)]\n"
    "\n"
)


def render_doc(model: Model) -> str:
    lines: list[str] = []
    if model.title:
        for line in model.title.strip().splitlines():
            lines.append(f"// {line}".rstrip())
        lines.append("//")

    if model.equations:
        for eq in model.equations:
            pretty = sp.pretty(eq.expr, use_unicode=True, num_columns=120)
            if "\n" in pretty:
                lines.append(f"//   {eq.label} =")
                for ln in pretty.splitlines():
                    lines.append(f"//     {ln}".rstrip())
            else:
                lines.append(f"//   {eq.label} = {pretty}")
        lines.append("//")

    if model.exports:
        lines.append("// Outputs:")
        for e in model.exports.values():
            lines.append(f"//   {e.name} : {e.rust_type}")
        lines.append("//")

    return HEADER + "\n".join(lines) + ("\n" if lines else "")
