[package]
name = "dies-controller"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

optimization_engine = "0.8.1"
nalgebra = { version = "0.32.3", features = ["serde-serialize"] }