[tasks.webui]
workspace = false
install_crate = "typeshare-cli"
script_runner = "@shell"
script = '''
typeshare . --lang=typescript --output-file=webui/src/bindings.ts
printf "export type Vector2 = [number, number];\nexport type Vector3 = [number, number, number];\nexport type Duration = number;\nexport type HashSet<T> = Array<T>;\n" >> webui/src/bindings.ts
sed -i.bak 's/data?: undefined//g' webui/src/bindings.ts && rm webui/src/bindings.ts.bak
cd webui
npm run build
'''
