[project]
name = "dies-framework-workspace"
version = "0.1.0"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.rye.workspace]

[tool.hatch.build.targets.wheel]
packages = ["strategy"]
