[package]
name = "dies-simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_rapier3d = { version = "0.22.0", features = [ "simd-stable", "debug-render-3d" ] }
bevy_panorbit_camera = "0.8.0"