[project]
name = "dies-test-strat"
version = "0.1.0"
dependencies = [
    "numpy>=1.26.3",
    "casadi>=3.6.4",
    "filterpy>=1.4.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
