[project]
name = "dies-test-strat"
version = "0.1.0"
dependencies = [
    "numpy>=1.26.3",
    "casadi>=3.6.4",
    "filterpy>=1.4.5",
    "snoop>=0.4.3",
    "pygame>=2.5.2",
    "scipy>=1.12.0",
    "shapely>=2.0.2",
    "scikit-learn>=1.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
