[package]
name = "workspace-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0.75", features = ["std"]}
dirs = "5.0.1"
lazy_static = "1.4.0"
