[package]
name = "dies-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
arc-swap = "1.6"
serde = { version = "1.0.192", features = ["derive"] }
ts-rs = "10.1.0"
