[package]
name = "dies-webui"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dies-core = { version = "0.1.0", path = "../dies-core" }
tracing = "0.1.40"
rocket = { version = "=0.5.0-rc.4", features = ["json"] }
tokio = "1.34.0"
