[package]
name = "dies-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.75"
dies-core = { version = "0.1.0", path = "../dies-core" }
dies-protos = { version = "0.1.0", path = "../dies-protos" }
dies-python-rt = { version = "0.1.0", path = "../dies-python-rt" }
dies-serial-client = { version = "0.1.0", path = "../dies-serial-client" }
dies-ssl-client = { version = "0.1.0", path = "../dies-ssl-client" }
dies-webui = { version = "0.1.0", path = "../dies-webui" }
dies-world = { version = "0.1.0", path = "../dies-world" }
env_logger = "0.10.1"
log = "0.4.20"
serialport = "4.2.2"
tokio = { version = "1.35.1", features = ["rt", "macros", "signal"] }
tokio-util = "0.7.10"
