[package]
name = "dies-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.75"
crossbeam = { version = "0.8.2", features = ["crossbeam-channel"] }
ctrlc = { version = "3.4.1", features = ["termination"] }
dies-core = { version = "0.1.0", path = "../dies-core" }
dies-ersim-env = { version = "0.1.0", path = "../dies-ersim-env" }
dies-python-rt = { version = "0.1.0", path = "../dies-python-rt" }
dies-world = { version = "0.1.0", path = "../dies-world" }
log = "0.4.20"
