[package]
name = "dies-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio = { version = "1.35.1", features = [
    "rt",
    "macros",
    "signal",
    "rt-multi-thread",
    "process",
] }
anyhow = "1.0.75"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
dies-core = { version = "0.1.0", path = "../dies-core" }
dies-serial-client = { version = "0.1.0", path = "../dies-serial-client" }
dies-ssl-client = { version = "0.1.0", path = "../dies-ssl-client" }
dies-simulator = { version = "0.1.0", path = "../dies-simulator" }
dirs = "5.0.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tracing-appender = "0.2.3"
nalgebra = "0.32.4"
dies-protos = { version = "0.1.0", path = "../dies-protos" }
dies-executor = { version = "0.1.0", path = "../dies-executor" }
dies-webui = { version = "0.1.0", path = "../dies-webui" }
