[package]
name = "dies-cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
dies-core = { version = "0.1.0", path = "../dies-core" }
dies-python-rt = { version = "0.1.0", path = "../dies-python-rt" }
dies-serial-client = { version = "0.1.0", path = "../dies-serial-client" }
dies-ssl-client = { version = "0.1.0", path = "../dies-ssl-client" }
dies-webui = { version = "0.1.0", path = "../dies-webui" }
dies-world = { version = "0.1.0", path = "../dies-world" }
dirs = "5.0.1"
tracing = "0.1.40"
tokio = { version = "1.35.1", features = ["rt", "macros", "signal"] }
tokio-util = "0.7.10"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tracing-appender = "0.2.3"
futures = "0.3.30"
