[package]
name = "dummy-strat"
version = "0.1.0"
edition.workspace = true

[dependencies]
dirs = "5.0.1"
ipc-channel = "0.19.0"
serde = { version = "1.0.215", features = ["derive"] }

[[bin]]
name = "server"
path = "strategy/dummy-strat/server.rs"

[[bin]]
name = "client"
path = "strategy/dummy-strat/client.rs"
