version: "3.1"

volumes:
  ssl-game-controller:


services:
  ssl-game-controller:
    image: robocupssl/ssl-game-controller:3.7.2
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    volumes:
      - "ssl-game-controller:/config:rw"
    network_mode: host
    ports:
      - "8081:8081/tcp"

  autoref-erforce:
    image: "roboticserlangen/autoref:commit-6f15f574ea80"
    command:
      - "--vision-port"
      - "10020"
      - "--tracker-port"
      - "11010"
      - "--gc-port"
      - "11003"
    network_mode: host

  simulator:
    image: "roboticserlangen/simulatorcli:commit-6a4e1c06533b"
    environment:
      GEOMETRY: "2020"
      REALISM: "RC2021"
    network_mode: host
    ports:
      - "10300/udp"
      - "10301/udp"
      - "10302/udp"

# networks:
#   simulator_net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.18.0.0/16
