"""Numerical parity: `pysim.solve` vs `crates::dies-mpc::solver::solve`.

Loads `golden.json` (generated by the Rust integration test
`cargo test -p dies-mpc --test dump_golden -- --ignored`), reconstructs
each scenario's inputs, runs the Python solver, and asserts that the
trajectories, controls, and final cost agree with the Rust ground truth.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from formulations.cost import m as cost_model
from formulations.dynamics import m as dyn_model

from pysim import build, solve, types


GOLDEN_PATH = Path(__file__).parent / "golden.json"


def _load_cases():
    if not GOLDEN_PATH.exists():
        pytest.skip(
            f"{GOLDEN_PATH} not found — regenerate with "
            "`cargo test -p dies-mpc --test dump_golden -- --ignored`"
        )
    with GOLDEN_PATH.open() as f:
        return json.load(f)["cases"]


def _params_from_json(d: dict) -> types.RobotParams:
    return types.RobotParams(
        tau=np.array(d["tau"]),
        accel_max=np.array(d["accel_max"]),
    )


def _target_from_json(d: dict) -> types.MpcTarget:
    p, v = d["p"], d["v"]
    w = d["weights"]
    return types.MpcTarget(
        p=types.Vec2(p[0], p[1]),
        v=types.Vec2(v[0], v[1]),
        weights=types.CostWeights(
            position=w["position"],
            velocity=w["velocity"],
            control=w["control"],
            control_smoothness=w["control_smoothness"],
        ),
    )


def _cfg_from_json(d: dict) -> types.SolverConfig:
    return types.SolverConfig(**d)


def _warm_from_json(d: dict | None) -> types.SolveResult | None:
    if d is None:
        return None
    return types.SolveResult(
        states=np.array(d["states"]),
        controls=np.array(d["controls"]),
        final_cost=0.0,
        iters=0,
        converged=False,
    )


@pytest.fixture(scope="module")
def callables():
    return build(dyn_model), build(cost_model)


@pytest.mark.parametrize("case", _load_cases(), ids=lambda c: c["name"])
def test_parity(case, callables):
    dyn, cost = callables
    inp = case["inputs"]
    out = case["outputs"]

    state = inp["state"]
    x0 = np.array([state["pos"][0], state["pos"][1], state["vel"][0], state["vel"][1]])
    target = _target_from_json(inp["target"])
    params = _params_from_json(inp["params"])
    cfg = _cfg_from_json(inp["cfg"])
    headings = np.array(inp["heading_traj"])
    warm = _warm_from_json(inp["warm_start"])

    result = solve(dyn, cost, x0, headings, target, params, warm_start=warm, cfg=cfg)

    rust_states = np.array(out["trajectory"]["states"])
    rust_controls = np.array(out["trajectory"]["controls"])
    rust_cost = out["final_cost"]
    rust_iters = out["iters"]
    rust_converged = out["converged"]

    # Tolerances: mm-scale states, controls in mm/s.
    np.testing.assert_allclose(
        result.controls, rust_controls, atol=1e-3, rtol=1e-6,
        err_msg=f"{case['name']}: controls mismatch",
    )
    np.testing.assert_allclose(
        result.states, rust_states, atol=1e-2, rtol=1e-6,
        err_msg=f"{case['name']}: states mismatch",
    )
    assert abs(result.final_cost - rust_cost) / max(abs(rust_cost), 1.0) < 1e-6, (
        f"{case['name']}: final_cost {result.final_cost} vs {rust_cost}"
    )
    # Iter counts can differ by 1 due to line-search ties; converged flag should match.
    assert abs(result.iters - rust_iters) <= 1, (
        f"{case['name']}: iters {result.iters} vs {rust_iters}"
    )
    assert result.converged == rust_converged, (
        f"{case['name']}: converged {result.converged} vs {rust_converged}"
    )
