name: Build docs

on:
  push:
    branches:
      - main
    paths: ["docs/**/*"]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: cargo install mdbook
      - run: cargo install mdbook-mermaid

      - run: mdbook build
        working-directory: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
